// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/error_code.proto
// Protobuf Java Version: 4.35.0

package com.platform.common;

@com.google.protobuf.Generated
public interface ErrorDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.ErrorDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 错误码
   * </pre>
   *
   * <code>.common.ErrorCode code = 1 [json_name = "code"];</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <pre>
   * 错误码
   * </pre>
   *
   * <code>.common.ErrorCode code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  com.platform.common.ErrorCode getCode();

  /**
   * <pre>
   * 内部错误消息
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 内部错误消息
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 用户友好消息
   * </pre>
   *
   * <code>string user_message = 3 [json_name = "userMessage"];</code>
   * @return The userMessage.
   */
  java.lang.String getUserMessage();
  /**
   * <pre>
   * 用户友好消息
   * </pre>
   *
   * <code>string user_message = 3 [json_name = "userMessage"];</code>
   * @return The bytes for userMessage.
   */
  com.google.protobuf.ByteString
      getUserMessageBytes();

  /**
   * <pre>
   * 额外详情
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 4 [json_name = "details"];</code>
   */
  int getDetailsCount();
  /**
   * <pre>
   * 额外详情
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 4 [json_name = "details"];</code>
   */
  boolean containsDetails(
      java.lang.String key);
  /**
   * Use {@link #getDetailsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getDetails();
  /**
   * <pre>
   * 额外详情
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 4 [json_name = "details"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDetailsMap();
  /**
   * <pre>
   * 额外详情
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 4 [json_name = "details"];</code>
   */
  /* nullable */
java.lang.String getDetailsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 额外详情
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 4 [json_name = "details"];</code>
   */
  java.lang.String getDetailsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * 请求追踪 ID
   * </pre>
   *
   * <code>string request_id = 5 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * 请求追踪 ID
   * </pre>
   *
   * <code>string request_id = 5 [json_name = "requestId"];</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * OpenTelemetry Trace ID
   * </pre>
   *
   * <code>string trace_id = 6 [json_name = "traceId"];</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <pre>
   * OpenTelemetry Trace ID
   * </pre>
   *
   * <code>string trace_id = 6 [json_name = "traceId"];</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <pre>
   * 错误发生时间戳
   * </pre>
   *
   * <code>int64 timestamp = 7 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 来源服务
   * </pre>
   *
   * <code>string service = 8 [json_name = "service"];</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <pre>
   * 来源服务
   * </pre>
   *
   * <code>string service = 8 [json_name = "service"];</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();
}
