// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: toolbus/tool_bus.proto
// Protobuf Java Version: 4.35.0

package com.platform.toolbus;

@com.google.protobuf.Generated
public interface ValidateToolInputResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:toolbus.ValidateToolInputResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.toolbus.RequestContext getContext();
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.toolbus.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <pre>
   * 是否有效
   * </pre>
   *
   * <code>bool valid = 2 [json_name = "valid"];</code>
   * @return The valid.
   */
  boolean getValid();

  /**
   * <pre>
   * 校验错误列表
   * </pre>
   *
   * <code>repeated .toolbus.ValidationError errors = 3 [json_name = "errors"];</code>
   */
  java.util.List<com.platform.toolbus.ValidationError> 
      getErrorsList();
  /**
   * <pre>
   * 校验错误列表
   * </pre>
   *
   * <code>repeated .toolbus.ValidationError errors = 3 [json_name = "errors"];</code>
   */
  com.platform.toolbus.ValidationError getErrors(int index);
  /**
   * <pre>
   * 校验错误列表
   * </pre>
   *
   * <code>repeated .toolbus.ValidationError errors = 3 [json_name = "errors"];</code>
   */
  int getErrorsCount();
  /**
   * <pre>
   * 校验错误列表
   * </pre>
   *
   * <code>repeated .toolbus.ValidationError errors = 3 [json_name = "errors"];</code>
   */
  java.util.List<? extends com.platform.toolbus.ValidationErrorOrBuilder> 
      getErrorsOrBuilderList();
  /**
   * <pre>
   * 校验错误列表
   * </pre>
   *
   * <code>repeated .toolbus.ValidationError errors = 3 [json_name = "errors"];</code>
   */
  com.platform.toolbus.ValidationErrorOrBuilder getErrorsOrBuilder(
      int index);

  /**
   * <pre>
   * 其他错误
   * </pre>
   *
   * <code>.common.ErrorDetail error = 4 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * 其他错误
   * </pre>
   *
   * <code>.common.ErrorDetail error = 4 [json_name = "error"];</code>
   * @return The error.
   */
  com.platform.common.ErrorDetail getError();
  /**
   * <pre>
   * 其他错误
   * </pre>
   *
   * <code>.common.ErrorDetail error = 4 [json_name = "error"];</code>
   */
  com.platform.common.ErrorDetailOrBuilder getErrorOrBuilder();
}
