// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model/model_gateway.proto
// Protobuf Java Version: 4.35.1

package com.platform.model;

@com.google.protobuf.Generated
public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.model.RequestContext getContext();
  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.model.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <pre>
   * 响应 ID
   * </pre>
   *
   * <code>string response_id = 2 [json_name = "responseId"];</code>
   * @return The responseId.
   */
  java.lang.String getResponseId();
  /**
   * <pre>
   * 响应 ID
   * </pre>
   *
   * <code>string response_id = 2 [json_name = "responseId"];</code>
   * @return The bytes for responseId.
   */
  com.google.protobuf.ByteString
      getResponseIdBytes();

  /**
   * <pre>
   * 响应内容
   * </pre>
   *
   * <code>string content = 3 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 响应内容
   * </pre>
   *
   * <code>string content = 3 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 多模态响应
   * </pre>
   *
   * <code>repeated .model.ContentPart parts = 4 [json_name = "parts"];</code>
   */
  java.util.List<com.platform.model.ContentPart> 
      getPartsList();
  /**
   * <pre>
   * 多模态响应
   * </pre>
   *
   * <code>repeated .model.ContentPart parts = 4 [json_name = "parts"];</code>
   */
  com.platform.model.ContentPart getParts(int index);
  /**
   * <pre>
   * 多模态响应
   * </pre>
   *
   * <code>repeated .model.ContentPart parts = 4 [json_name = "parts"];</code>
   */
  int getPartsCount();
  /**
   * <pre>
   * 多模态响应
   * </pre>
   *
   * <code>repeated .model.ContentPart parts = 4 [json_name = "parts"];</code>
   */
  java.util.List<? extends com.platform.model.ContentPartOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <pre>
   * 多模态响应
   * </pre>
   *
   * <code>repeated .model.ContentPart parts = 4 [json_name = "parts"];</code>
   */
  com.platform.model.ContentPartOrBuilder getPartsOrBuilder(
      int index);

  /**
   * <pre>
   * 工具调用
   * </pre>
   *
   * <code>repeated .model.ToolCallResult tool_calls = 5 [json_name = "toolCalls"];</code>
   */
  java.util.List<com.platform.model.ToolCallResult> 
      getToolCallsList();
  /**
   * <pre>
   * 工具调用
   * </pre>
   *
   * <code>repeated .model.ToolCallResult tool_calls = 5 [json_name = "toolCalls"];</code>
   */
  com.platform.model.ToolCallResult getToolCalls(int index);
  /**
   * <pre>
   * 工具调用
   * </pre>
   *
   * <code>repeated .model.ToolCallResult tool_calls = 5 [json_name = "toolCalls"];</code>
   */
  int getToolCallsCount();
  /**
   * <pre>
   * 工具调用
   * </pre>
   *
   * <code>repeated .model.ToolCallResult tool_calls = 5 [json_name = "toolCalls"];</code>
   */
  java.util.List<? extends com.platform.model.ToolCallResultOrBuilder> 
      getToolCallsOrBuilderList();
  /**
   * <pre>
   * 工具调用
   * </pre>
   *
   * <code>repeated .model.ToolCallResult tool_calls = 5 [json_name = "toolCalls"];</code>
   */
  com.platform.model.ToolCallResultOrBuilder getToolCallsOrBuilder(
      int index);

  /**
   * <pre>
   * 模型信息
   * </pre>
   *
   * <code>string model_used = 6 [json_name = "modelUsed"];</code>
   * @return The modelUsed.
   */
  java.lang.String getModelUsed();
  /**
   * <pre>
   * 模型信息
   * </pre>
   *
   * <code>string model_used = 6 [json_name = "modelUsed"];</code>
   * @return The bytes for modelUsed.
   */
  com.google.protobuf.ByteString
      getModelUsedBytes();

  /**
   * <pre>
   * 提供商：qwen / glm / kimi / deepseek
   * </pre>
   *
   * <code>string provider = 7 [json_name = "provider"];</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <pre>
   * 提供商：qwen / glm / kimi / deepseek
   * </pre>
   *
   * <code>string provider = 7 [json_name = "provider"];</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <pre>
   * Token 统计
   * </pre>
   *
   * <code>int32 prompt_tokens = 8 [json_name = "promptTokens"];</code>
   * @return The promptTokens.
   */
  int getPromptTokens();

  /**
   * <code>int32 completion_tokens = 9 [json_name = "completionTokens"];</code>
   * @return The completionTokens.
   */
  int getCompletionTokens();

  /**
   * <code>int32 total_tokens = 10 [json_name = "totalTokens"];</code>
   * @return The totalTokens.
   */
  int getTotalTokens();

  /**
   * <pre>
   * 缓存的 Prompt Tokens
   * </pre>
   *
   * <code>int32 cached_tokens = 11 [json_name = "cachedTokens"];</code>
   * @return The cachedTokens.
   */
  int getCachedTokens();

  /**
   * <pre>
   * 成本
   * </pre>
   *
   * <code>float cost_usd = 12 [json_name = "costUsd"];</code>
   * @return The costUsd.
   */
  float getCostUsd();

  /**
   * <pre>
   * 元信息
   * </pre>
   *
   * <code>string finish_reason = 13 [json_name = "finishReason"];</code>
   * @return The finishReason.
   */
  java.lang.String getFinishReason();
  /**
   * <pre>
   * 元信息
   * </pre>
   *
   * <code>string finish_reason = 13 [json_name = "finishReason"];</code>
   * @return The bytes for finishReason.
   */
  com.google.protobuf.ByteString
      getFinishReasonBytes();

  /**
   * <code>int32 latency_ms = 14 [json_name = "latencyMs"];</code>
   * @return The latencyMs.
   */
  int getLatencyMs();

  /**
   * <code>int64 created_at = 15 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <code>.common.ErrorDetail error = 16 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.common.ErrorDetail error = 16 [json_name = "error"];</code>
   * @return The error.
   */
  com.platform.common.ErrorDetail getError();
  /**
   * <code>.common.ErrorDetail error = 16 [json_name = "error"];</code>
   */
  com.platform.common.ErrorDetailOrBuilder getErrorOrBuilder();
}
