// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model/model_gateway.proto
// Protobuf Java Version: 4.35.1

package com.platform.model;

/**
 * <pre>
 * QuotaLevel - 配额层级
 * </pre>
 *
 * Protobuf enum {@code model.QuotaLevel}
 */
@com.google.protobuf.Generated
public enum QuotaLevel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>QUOTA_LEVEL_UNSPECIFIED = 0;</code>
   */
  QUOTA_LEVEL_UNSPECIFIED(0),
  /**
   * <pre>
   * 单会话
   * </pre>
   *
   * <code>QUOTA_LEVEL_SESSION = 1;</code>
   */
  QUOTA_LEVEL_SESSION(1),
  /**
   * <pre>
   * 用户日预算
   * </pre>
   *
   * <code>QUOTA_LEVEL_USER = 2;</code>
   */
  QUOTA_LEVEL_USER(2),
  /**
   * <pre>
   * 租户日预算
   * </pre>
   *
   * <code>QUOTA_LEVEL_TENANT = 3;</code>
   */
  QUOTA_LEVEL_TENANT(3),
  /**
   * <pre>
   * 全局日预算
   * </pre>
   *
   * <code>QUOTA_LEVEL_GLOBAL = 4;</code>
   */
  QUOTA_LEVEL_GLOBAL(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "QuotaLevel");
  }
  /**
   * <code>QUOTA_LEVEL_UNSPECIFIED = 0;</code>
   */
  public static final int QUOTA_LEVEL_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * 单会话
   * </pre>
   *
   * <code>QUOTA_LEVEL_SESSION = 1;</code>
   */
  public static final int QUOTA_LEVEL_SESSION_VALUE = 1;
  /**
   * <pre>
   * 用户日预算
   * </pre>
   *
   * <code>QUOTA_LEVEL_USER = 2;</code>
   */
  public static final int QUOTA_LEVEL_USER_VALUE = 2;
  /**
   * <pre>
   * 租户日预算
   * </pre>
   *
   * <code>QUOTA_LEVEL_TENANT = 3;</code>
   */
  public static final int QUOTA_LEVEL_TENANT_VALUE = 3;
  /**
   * <pre>
   * 全局日预算
   * </pre>
   *
   * <code>QUOTA_LEVEL_GLOBAL = 4;</code>
   */
  public static final int QUOTA_LEVEL_GLOBAL_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static QuotaLevel valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static QuotaLevel forNumber(int value) {
    switch (value) {
      case 0: return QUOTA_LEVEL_UNSPECIFIED;
      case 1: return QUOTA_LEVEL_SESSION;
      case 2: return QUOTA_LEVEL_USER;
      case 3: return QUOTA_LEVEL_TENANT;
      case 4: return QUOTA_LEVEL_GLOBAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<QuotaLevel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      QuotaLevel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<QuotaLevel>() {
          public QuotaLevel findValueByNumber(int number) {
            return QuotaLevel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.platform.model.ModelGateway.getDescriptor().getEnumType(0);
  }

  private static final QuotaLevel[] VALUES = values();

  public static QuotaLevel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private QuotaLevel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:model.QuotaLevel)
}

