// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model/model_gateway.proto
// Protobuf Java Version: 4.35.1

package com.platform.model;

@com.google.protobuf.Generated
public interface ToolDefinitionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ToolDefinition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * function
   * </pre>
   *
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * function
   * </pre>
   *
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * JSON Schema 格式
   * </pre>
   *
   * <code>string parameters_schema = 4 [json_name = "parametersSchema"];</code>
   * @return The parametersSchema.
   */
  java.lang.String getParametersSchema();
  /**
   * <pre>
   * JSON Schema 格式
   * </pre>
   *
   * <code>string parameters_schema = 4 [json_name = "parametersSchema"];</code>
   * @return The bytes for parametersSchema.
   */
  com.google.protobuf.ByteString
      getParametersSchemaBytes();
}
