// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: toolbus/tool_bus.proto
// Protobuf Java Version: 4.35.1

package com.platform.toolbus;

@com.google.protobuf.Generated
public interface GetToolInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:toolbus.GetToolInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.toolbus.RequestContext getContext();
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.toolbus.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <code>string tool_name = 2 [json_name = "toolName"];</code>
   * @return The toolName.
   */
  java.lang.String getToolName();
  /**
   * <code>string tool_name = 2 [json_name = "toolName"];</code>
   * @return The bytes for toolName.
   */
  com.google.protobuf.ByteString
      getToolNameBytes();

  /**
   * <pre>
   * 可选，默认 latest
   * </pre>
   *
   * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
   * @return The toolVersion.
   */
  java.lang.String getToolVersion();
  /**
   * <pre>
   * 可选，默认 latest
   * </pre>
   *
   * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
   * @return The bytes for toolVersion.
   */
  com.google.protobuf.ByteString
      getToolVersionBytes();
}
