// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: toolbus/tool_bus.proto
// Protobuf Java Version: 4.35.1

package com.platform.toolbus;

@com.google.protobuf.Generated
public interface GetToolInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:toolbus.GetToolInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.toolbus.RequestContext getContext();
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.toolbus.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <code>.toolbus.ToolInfo tool = 2 [json_name = "tool"];</code>
   * @return Whether the tool field is set.
   */
  boolean hasTool();
  /**
   * <code>.toolbus.ToolInfo tool = 2 [json_name = "tool"];</code>
   * @return The tool.
   */
  com.platform.toolbus.ToolInfo getTool();
  /**
   * <code>.toolbus.ToolInfo tool = 2 [json_name = "tool"];</code>
   */
  com.platform.toolbus.ToolInfoOrBuilder getToolOrBuilder();

  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 3 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 3 [json_name = "error"];</code>
   * @return The error.
   */
  com.platform.common.ErrorDetail getError();
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 3 [json_name = "error"];</code>
   */
  com.platform.common.ErrorDetailOrBuilder getErrorOrBuilder();
}
