// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: toolbus/tool_bus.proto
// Protobuf Java Version: 4.35.1

package com.platform.toolbus;

/**
 * <pre>
 * ToolExecuteRequest - 工具执行请求
 * </pre>
 *
 * Protobuf type {@code toolbus.ToolExecuteRequest}
 */
@com.google.protobuf.Generated
public final class ToolExecuteRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:toolbus.ToolExecuteRequest)
    ToolExecuteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ToolExecuteRequest");
  }
  // Use ToolExecuteRequest.newBuilder() to construct.
  private ToolExecuteRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ToolExecuteRequest() {
    toolName_ = "";
    toolVersion_ = "";
    argumentsJson_ = "";
    cacheKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolExecuteRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolExecuteRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolExecuteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platform.toolbus.ToolExecuteRequest.class, com.platform.toolbus.ToolExecuteRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CONTEXT_FIELD_NUMBER = 1;
  private com.platform.toolbus.RequestContext context_;
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  @java.lang.Override
  public boolean hasContext() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  @java.lang.Override
  public com.platform.toolbus.RequestContext getContext() {
    return context_ == null ? com.platform.toolbus.RequestContext.getDefaultInstance() : context_;
  }
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   */
  @java.lang.Override
  public com.platform.toolbus.RequestContextOrBuilder getContextOrBuilder() {
    return context_ == null ? com.platform.toolbus.RequestContext.getDefaultInstance() : context_;
  }

  public static final int TOOL_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object toolName_ = "";
  /**
   * <pre>
   * 工具名称
   * </pre>
   *
   * <code>string tool_name = 2 [json_name = "toolName"];</code>
   * @return The toolName.
   */
  @java.lang.Override
  public java.lang.String getToolName() {
    java.lang.Object ref = toolName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toolName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 工具名称
   * </pre>
   *
   * <code>string tool_name = 2 [json_name = "toolName"];</code>
   * @return The bytes for toolName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToolNameBytes() {
    java.lang.Object ref = toolName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toolName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOOL_VERSION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object toolVersion_ = "";
  /**
   * <pre>
   * 工具版本（默认 latest）
   * </pre>
   *
   * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
   * @return The toolVersion.
   */
  @java.lang.Override
  public java.lang.String getToolVersion() {
    java.lang.Object ref = toolVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toolVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 工具版本（默认 latest）
   * </pre>
   *
   * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
   * @return The bytes for toolVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToolVersionBytes() {
    java.lang.Object ref = toolVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toolVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARGUMENTS_JSON_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object argumentsJson_ = "";
  /**
   * <pre>
   * 工具参数（JSON 字串）
   * </pre>
   *
   * <code>string arguments_json = 4 [json_name = "argumentsJson"];</code>
   * @return The argumentsJson.
   */
  @java.lang.Override
  public java.lang.String getArgumentsJson() {
    java.lang.Object ref = argumentsJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      argumentsJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 工具参数（JSON 字串）
   * </pre>
   *
   * <code>string arguments_json = 4 [json_name = "argumentsJson"];</code>
   * @return The bytes for argumentsJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArgumentsJsonBytes() {
    java.lang.Object ref = argumentsJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      argumentsJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEOUT_MS_FIELD_NUMBER = 5;
  private int timeoutMs_ = 0;
  /**
   * <pre>
   * 执行控制
   * </pre>
   *
   * <code>int32 timeout_ms = 5 [json_name = "timeoutMs"];</code>
   * @return The timeoutMs.
   */
  @java.lang.Override
  public int getTimeoutMs() {
    return timeoutMs_;
  }

  public static final int SKIP_RISK_CHECK_FIELD_NUMBER = 6;
  private boolean skipRiskCheck_ = false;
  /**
   * <pre>
   * 跳过风控检查（仅测试环境）
   * </pre>
   *
   * <code>bool skip_risk_check = 6 [json_name = "skipRiskCheck"];</code>
   * @return The skipRiskCheck.
   */
  @java.lang.Override
  public boolean getSkipRiskCheck() {
    return skipRiskCheck_;
  }

  public static final int SKIP_APPROVAL_FIELD_NUMBER = 7;
  private boolean skipApproval_ = false;
  /**
   * <pre>
   * 跳过审批（仅测试环境）
   * </pre>
   *
   * <code>bool skip_approval = 7 [json_name = "skipApproval"];</code>
   * @return The skipApproval.
   */
  @java.lang.Override
  public boolean getSkipApproval() {
    return skipApproval_;
  }

  public static final int USE_CACHE_FIELD_NUMBER = 8;
  private boolean useCache_ = false;
  /**
   * <pre>
   * 缓存控制
   * </pre>
   *
   * <code>bool use_cache = 8 [json_name = "useCache"];</code>
   * @return The useCache.
   */
  @java.lang.Override
  public boolean getUseCache() {
    return useCache_;
  }

  public static final int CACHE_KEY_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cacheKey_ = "";
  /**
   * <pre>
   * 自定义缓存键
   * </pre>
   *
   * <code>string cache_key = 9 [json_name = "cacheKey"];</code>
   * @return The cacheKey.
   */
  @java.lang.Override
  public java.lang.String getCacheKey() {
    java.lang.Object ref = cacheKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cacheKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 自定义缓存键
   * </pre>
   *
   * <code>string cache_key = 9 [json_name = "cacheKey"];</code>
   * @return The bytes for cacheKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCacheKeyBytes() {
    java.lang.Object ref = cacheKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cacheKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getContext());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toolName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, toolName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toolVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, toolVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(argumentsJson_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, argumentsJson_);
    }
    if (timeoutMs_ != 0) {
      output.writeInt32(5, timeoutMs_);
    }
    if (skipRiskCheck_ != false) {
      output.writeBool(6, skipRiskCheck_);
    }
    if (skipApproval_ != false) {
      output.writeBool(7, skipApproval_);
    }
    if (useCache_ != false) {
      output.writeBool(8, useCache_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cacheKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, cacheKey_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContext());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toolName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, toolName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toolVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, toolVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(argumentsJson_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, argumentsJson_);
    }
    if (timeoutMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, timeoutMs_);
    }
    if (skipRiskCheck_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, skipRiskCheck_);
    }
    if (skipApproval_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, skipApproval_);
    }
    if (useCache_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, useCache_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cacheKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, cacheKey_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platform.toolbus.ToolExecuteRequest)) {
      return super.equals(obj);
    }
    com.platform.toolbus.ToolExecuteRequest other = (com.platform.toolbus.ToolExecuteRequest) obj;

    if (hasContext() != other.hasContext()) return false;
    if (hasContext()) {
      if (!getContext()
          .equals(other.getContext())) return false;
    }
    if (!getToolName()
        .equals(other.getToolName())) return false;
    if (!getToolVersion()
        .equals(other.getToolVersion())) return false;
    if (!getArgumentsJson()
        .equals(other.getArgumentsJson())) return false;
    if (getTimeoutMs()
        != other.getTimeoutMs()) return false;
    if (getSkipRiskCheck()
        != other.getSkipRiskCheck()) return false;
    if (getSkipApproval()
        != other.getSkipApproval()) return false;
    if (getUseCache()
        != other.getUseCache()) return false;
    if (!getCacheKey()
        .equals(other.getCacheKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContext()) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
    }
    hash = (37 * hash) + TOOL_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getToolName().hashCode();
    hash = (37 * hash) + TOOL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getToolVersion().hashCode();
    hash = (37 * hash) + ARGUMENTS_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getArgumentsJson().hashCode();
    hash = (37 * hash) + TIMEOUT_MS_FIELD_NUMBER;
    hash = (53 * hash) + getTimeoutMs();
    hash = (37 * hash) + SKIP_RISK_CHECK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSkipRiskCheck());
    hash = (37 * hash) + SKIP_APPROVAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSkipApproval());
    hash = (37 * hash) + USE_CACHE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUseCache());
    hash = (37 * hash) + CACHE_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getCacheKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platform.toolbus.ToolExecuteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.platform.toolbus.ToolExecuteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.platform.toolbus.ToolExecuteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.platform.toolbus.ToolExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platform.toolbus.ToolExecuteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ToolExecuteRequest - 工具执行请求
   * </pre>
   *
   * Protobuf type {@code toolbus.ToolExecuteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:toolbus.ToolExecuteRequest)
      com.platform.toolbus.ToolExecuteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolExecuteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolExecuteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platform.toolbus.ToolExecuteRequest.class, com.platform.toolbus.ToolExecuteRequest.Builder.class);
    }

    // Construct using com.platform.toolbus.ToolExecuteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetContextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      toolName_ = "";
      toolVersion_ = "";
      argumentsJson_ = "";
      timeoutMs_ = 0;
      skipRiskCheck_ = false;
      skipApproval_ = false;
      useCache_ = false;
      cacheKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolExecuteRequest_descriptor;
    }

    @java.lang.Override
    public com.platform.toolbus.ToolExecuteRequest getDefaultInstanceForType() {
      return com.platform.toolbus.ToolExecuteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.platform.toolbus.ToolExecuteRequest build() {
      com.platform.toolbus.ToolExecuteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platform.toolbus.ToolExecuteRequest buildPartial() {
      com.platform.toolbus.ToolExecuteRequest result = new com.platform.toolbus.ToolExecuteRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.platform.toolbus.ToolExecuteRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.context_ = contextBuilder_ == null
            ? context_
            : contextBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.toolName_ = toolName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.toolVersion_ = toolVersion_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.argumentsJson_ = argumentsJson_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timeoutMs_ = timeoutMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.skipRiskCheck_ = skipRiskCheck_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.skipApproval_ = skipApproval_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.useCache_ = useCache_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.cacheKey_ = cacheKey_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platform.toolbus.ToolExecuteRequest) {
        return mergeFrom((com.platform.toolbus.ToolExecuteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platform.toolbus.ToolExecuteRequest other) {
      if (other == com.platform.toolbus.ToolExecuteRequest.getDefaultInstance()) return this;
      if (other.hasContext()) {
        mergeContext(other.getContext());
      }
      if (!other.getToolName().isEmpty()) {
        toolName_ = other.toolName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getToolVersion().isEmpty()) {
        toolVersion_ = other.toolVersion_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getArgumentsJson().isEmpty()) {
        argumentsJson_ = other.argumentsJson_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getTimeoutMs() != 0) {
        setTimeoutMs(other.getTimeoutMs());
      }
      if (other.getSkipRiskCheck() != false) {
        setSkipRiskCheck(other.getSkipRiskCheck());
      }
      if (other.getSkipApproval() != false) {
        setSkipApproval(other.getSkipApproval());
      }
      if (other.getUseCache() != false) {
        setUseCache(other.getUseCache());
      }
      if (!other.getCacheKey().isEmpty()) {
        cacheKey_ = other.cacheKey_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetContextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              toolName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              toolVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              argumentsJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              timeoutMs_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              skipRiskCheck_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              skipApproval_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              useCache_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              cacheKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.platform.toolbus.RequestContext context_;
    private com.google.protobuf.SingleFieldBuilder<
        com.platform.toolbus.RequestContext, com.platform.toolbus.RequestContext.Builder, com.platform.toolbus.RequestContextOrBuilder> contextBuilder_;
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     * @return Whether the context field is set.
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     * @return The context.
     */
    public com.platform.toolbus.RequestContext getContext() {
      if (contextBuilder_ == null) {
        return context_ == null ? com.platform.toolbus.RequestContext.getDefaultInstance() : context_;
      } else {
        return contextBuilder_.getMessage();
      }
    }
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder setContext(com.platform.toolbus.RequestContext value) {
      if (contextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        context_ = value;
      } else {
        contextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder setContext(
        com.platform.toolbus.RequestContext.Builder builderForValue) {
      if (contextBuilder_ == null) {
        context_ = builderForValue.build();
      } else {
        contextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder mergeContext(com.platform.toolbus.RequestContext value) {
      if (contextBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          context_ != null &&
          context_ != com.platform.toolbus.RequestContext.getDefaultInstance()) {
          getContextBuilder().mergeFrom(value);
        } else {
          context_ = value;
        }
      } else {
        contextBuilder_.mergeFrom(value);
      }
      if (context_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder clearContext() {
      bitField0_ = (bitField0_ & ~0x00000001);
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     */
    public com.platform.toolbus.RequestContext.Builder getContextBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     */
    public com.platform.toolbus.RequestContextOrBuilder getContextOrBuilder() {
      if (contextBuilder_ != null) {
        return contextBuilder_.getMessageOrBuilder();
      } else {
        return context_ == null ?
            com.platform.toolbus.RequestContext.getDefaultInstance() : context_;
      }
    }
    /**
     * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.platform.toolbus.RequestContext, com.platform.toolbus.RequestContext.Builder, com.platform.toolbus.RequestContextOrBuilder> 
        internalGetContextFieldBuilder() {
      if (contextBuilder_ == null) {
        contextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.platform.toolbus.RequestContext, com.platform.toolbus.RequestContext.Builder, com.platform.toolbus.RequestContextOrBuilder>(
                getContext(),
                getParentForChildren(),
                isClean());
        context_ = null;
      }
      return contextBuilder_;
    }

    private java.lang.Object toolName_ = "";
    /**
     * <pre>
     * 工具名称
     * </pre>
     *
     * <code>string tool_name = 2 [json_name = "toolName"];</code>
     * @return The toolName.
     */
    public java.lang.String getToolName() {
      java.lang.Object ref = toolName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toolName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 工具名称
     * </pre>
     *
     * <code>string tool_name = 2 [json_name = "toolName"];</code>
     * @return The bytes for toolName.
     */
    public com.google.protobuf.ByteString
        getToolNameBytes() {
      java.lang.Object ref = toolName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toolName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 工具名称
     * </pre>
     *
     * <code>string tool_name = 2 [json_name = "toolName"];</code>
     * @param value The toolName to set.
     * @return This builder for chaining.
     */
    public Builder setToolName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      toolName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 工具名称
     * </pre>
     *
     * <code>string tool_name = 2 [json_name = "toolName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearToolName() {
      toolName_ = getDefaultInstance().getToolName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 工具名称
     * </pre>
     *
     * <code>string tool_name = 2 [json_name = "toolName"];</code>
     * @param value The bytes for toolName to set.
     * @return This builder for chaining.
     */
    public Builder setToolNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      toolName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object toolVersion_ = "";
    /**
     * <pre>
     * 工具版本（默认 latest）
     * </pre>
     *
     * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
     * @return The toolVersion.
     */
    public java.lang.String getToolVersion() {
      java.lang.Object ref = toolVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toolVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 工具版本（默认 latest）
     * </pre>
     *
     * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
     * @return The bytes for toolVersion.
     */
    public com.google.protobuf.ByteString
        getToolVersionBytes() {
      java.lang.Object ref = toolVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toolVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 工具版本（默认 latest）
     * </pre>
     *
     * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
     * @param value The toolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setToolVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      toolVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 工具版本（默认 latest）
     * </pre>
     *
     * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearToolVersion() {
      toolVersion_ = getDefaultInstance().getToolVersion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 工具版本（默认 latest）
     * </pre>
     *
     * <code>string tool_version = 3 [json_name = "toolVersion"];</code>
     * @param value The bytes for toolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setToolVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      toolVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object argumentsJson_ = "";
    /**
     * <pre>
     * 工具参数（JSON 字串）
     * </pre>
     *
     * <code>string arguments_json = 4 [json_name = "argumentsJson"];</code>
     * @return The argumentsJson.
     */
    public java.lang.String getArgumentsJson() {
      java.lang.Object ref = argumentsJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        argumentsJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 工具参数（JSON 字串）
     * </pre>
     *
     * <code>string arguments_json = 4 [json_name = "argumentsJson"];</code>
     * @return The bytes for argumentsJson.
     */
    public com.google.protobuf.ByteString
        getArgumentsJsonBytes() {
      java.lang.Object ref = argumentsJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        argumentsJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 工具参数（JSON 字串）
     * </pre>
     *
     * <code>string arguments_json = 4 [json_name = "argumentsJson"];</code>
     * @param value The argumentsJson to set.
     * @return This builder for chaining.
     */
    public Builder setArgumentsJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      argumentsJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 工具参数（JSON 字串）
     * </pre>
     *
     * <code>string arguments_json = 4 [json_name = "argumentsJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArgumentsJson() {
      argumentsJson_ = getDefaultInstance().getArgumentsJson();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 工具参数（JSON 字串）
     * </pre>
     *
     * <code>string arguments_json = 4 [json_name = "argumentsJson"];</code>
     * @param value The bytes for argumentsJson to set.
     * @return This builder for chaining.
     */
    public Builder setArgumentsJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      argumentsJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int timeoutMs_ ;
    /**
     * <pre>
     * 执行控制
     * </pre>
     *
     * <code>int32 timeout_ms = 5 [json_name = "timeoutMs"];</code>
     * @return The timeoutMs.
     */
    @java.lang.Override
    public int getTimeoutMs() {
      return timeoutMs_;
    }
    /**
     * <pre>
     * 执行控制
     * </pre>
     *
     * <code>int32 timeout_ms = 5 [json_name = "timeoutMs"];</code>
     * @param value The timeoutMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimeoutMs(int value) {

      timeoutMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 执行控制
     * </pre>
     *
     * <code>int32 timeout_ms = 5 [json_name = "timeoutMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeoutMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timeoutMs_ = 0;
      onChanged();
      return this;
    }

    private boolean skipRiskCheck_ ;
    /**
     * <pre>
     * 跳过风控检查（仅测试环境）
     * </pre>
     *
     * <code>bool skip_risk_check = 6 [json_name = "skipRiskCheck"];</code>
     * @return The skipRiskCheck.
     */
    @java.lang.Override
    public boolean getSkipRiskCheck() {
      return skipRiskCheck_;
    }
    /**
     * <pre>
     * 跳过风控检查（仅测试环境）
     * </pre>
     *
     * <code>bool skip_risk_check = 6 [json_name = "skipRiskCheck"];</code>
     * @param value The skipRiskCheck to set.
     * @return This builder for chaining.
     */
    public Builder setSkipRiskCheck(boolean value) {

      skipRiskCheck_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跳过风控检查（仅测试环境）
     * </pre>
     *
     * <code>bool skip_risk_check = 6 [json_name = "skipRiskCheck"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSkipRiskCheck() {
      bitField0_ = (bitField0_ & ~0x00000020);
      skipRiskCheck_ = false;
      onChanged();
      return this;
    }

    private boolean skipApproval_ ;
    /**
     * <pre>
     * 跳过审批（仅测试环境）
     * </pre>
     *
     * <code>bool skip_approval = 7 [json_name = "skipApproval"];</code>
     * @return The skipApproval.
     */
    @java.lang.Override
    public boolean getSkipApproval() {
      return skipApproval_;
    }
    /**
     * <pre>
     * 跳过审批（仅测试环境）
     * </pre>
     *
     * <code>bool skip_approval = 7 [json_name = "skipApproval"];</code>
     * @param value The skipApproval to set.
     * @return This builder for chaining.
     */
    public Builder setSkipApproval(boolean value) {

      skipApproval_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跳过审批（仅测试环境）
     * </pre>
     *
     * <code>bool skip_approval = 7 [json_name = "skipApproval"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSkipApproval() {
      bitField0_ = (bitField0_ & ~0x00000040);
      skipApproval_ = false;
      onChanged();
      return this;
    }

    private boolean useCache_ ;
    /**
     * <pre>
     * 缓存控制
     * </pre>
     *
     * <code>bool use_cache = 8 [json_name = "useCache"];</code>
     * @return The useCache.
     */
    @java.lang.Override
    public boolean getUseCache() {
      return useCache_;
    }
    /**
     * <pre>
     * 缓存控制
     * </pre>
     *
     * <code>bool use_cache = 8 [json_name = "useCache"];</code>
     * @param value The useCache to set.
     * @return This builder for chaining.
     */
    public Builder setUseCache(boolean value) {

      useCache_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 缓存控制
     * </pre>
     *
     * <code>bool use_cache = 8 [json_name = "useCache"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUseCache() {
      bitField0_ = (bitField0_ & ~0x00000080);
      useCache_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object cacheKey_ = "";
    /**
     * <pre>
     * 自定义缓存键
     * </pre>
     *
     * <code>string cache_key = 9 [json_name = "cacheKey"];</code>
     * @return The cacheKey.
     */
    public java.lang.String getCacheKey() {
      java.lang.Object ref = cacheKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cacheKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 自定义缓存键
     * </pre>
     *
     * <code>string cache_key = 9 [json_name = "cacheKey"];</code>
     * @return The bytes for cacheKey.
     */
    public com.google.protobuf.ByteString
        getCacheKeyBytes() {
      java.lang.Object ref = cacheKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cacheKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 自定义缓存键
     * </pre>
     *
     * <code>string cache_key = 9 [json_name = "cacheKey"];</code>
     * @param value The cacheKey to set.
     * @return This builder for chaining.
     */
    public Builder setCacheKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cacheKey_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义缓存键
     * </pre>
     *
     * <code>string cache_key = 9 [json_name = "cacheKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCacheKey() {
      cacheKey_ = getDefaultInstance().getCacheKey();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义缓存键
     * </pre>
     *
     * <code>string cache_key = 9 [json_name = "cacheKey"];</code>
     * @param value The bytes for cacheKey to set.
     * @return This builder for chaining.
     */
    public Builder setCacheKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cacheKey_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:toolbus.ToolExecuteRequest)
  }

  // @@protoc_insertion_point(class_scope:toolbus.ToolExecuteRequest)
  private static final com.platform.toolbus.ToolExecuteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platform.toolbus.ToolExecuteRequest();
  }

  public static com.platform.toolbus.ToolExecuteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ToolExecuteRequest>
      PARSER = new com.google.protobuf.AbstractParser<ToolExecuteRequest>() {
    @java.lang.Override
    public ToolExecuteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ToolExecuteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ToolExecuteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platform.toolbus.ToolExecuteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

