// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: toolbus/tool_bus.proto
// Protobuf Java Version: 4.35.1

package com.platform.toolbus;

/**
 * <pre>
 * ToolInfo - 工具信息
 * </pre>
 *
 * Protobuf type {@code toolbus.ToolInfo}
 */
@com.google.protobuf.Generated
public final class ToolInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:toolbus.ToolInfo)
    ToolInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ToolInfo");
  }
  // Use ToolInfo.newBuilder() to construct.
  private ToolInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ToolInfo() {
    name_ = "";
    version_ = "";
    category_ = "";
    description_ = "";
    inputSchemaJson_ = "";
    outputSchemaJson_ = "";
    riskLevel_ = "";
    approvalCondition_ = "";
    deprecatedMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolInfo_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platform.toolbus.ToolInfo.class, com.platform.toolbus.ToolInfo.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 2 [json_name = "version"];</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 2 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object category_ = "";
  /**
   * <pre>
   * query / write / external
   * </pre>
   *
   * <code>string category = 3 [json_name = "category"];</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * query / write / external
   * </pre>
   *
   * <code>string category = 3 [json_name = "category"];</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_SCHEMA_JSON_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object inputSchemaJson_ = "";
  /**
   * <pre>
   * 输入 Schema（JSON）
   * </pre>
   *
   * <code>string input_schema_json = 5 [json_name = "inputSchemaJson"];</code>
   * @return The inputSchemaJson.
   */
  @java.lang.Override
  public java.lang.String getInputSchemaJson() {
    java.lang.Object ref = inputSchemaJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inputSchemaJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 输入 Schema（JSON）
   * </pre>
   *
   * <code>string input_schema_json = 5 [json_name = "inputSchemaJson"];</code>
   * @return The bytes for inputSchemaJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputSchemaJsonBytes() {
    java.lang.Object ref = inputSchemaJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inputSchemaJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTPUT_SCHEMA_JSON_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object outputSchemaJson_ = "";
  /**
   * <pre>
   * 输出 Schema（JSON）
   * </pre>
   *
   * <code>string output_schema_json = 6 [json_name = "outputSchemaJson"];</code>
   * @return The outputSchemaJson.
   */
  @java.lang.Override
  public java.lang.String getOutputSchemaJson() {
    java.lang.Object ref = outputSchemaJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputSchemaJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 输出 Schema（JSON）
   * </pre>
   *
   * <code>string output_schema_json = 6 [json_name = "outputSchemaJson"];</code>
   * @return The bytes for outputSchemaJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputSchemaJsonBytes() {
    java.lang.Object ref = outputSchemaJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputSchemaJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RISK_LEVEL_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object riskLevel_ = "";
  /**
   * <pre>
   * 风险等级
   * </pre>
   *
   * <code>string risk_level = 7 [json_name = "riskLevel"];</code>
   * @return The riskLevel.
   */
  @java.lang.Override
  public java.lang.String getRiskLevel() {
    java.lang.Object ref = riskLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      riskLevel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 风险等级
   * </pre>
   *
   * <code>string risk_level = 7 [json_name = "riskLevel"];</code>
   * @return The bytes for riskLevel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRiskLevelBytes() {
    java.lang.Object ref = riskLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      riskLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUIRES_APPROVAL_FIELD_NUMBER = 8;
  private boolean requiresApproval_ = false;
  /**
   * <pre>
   * 是否需要审批
   * </pre>
   *
   * <code>bool requires_approval = 8 [json_name = "requiresApproval"];</code>
   * @return The requiresApproval.
   */
  @java.lang.Override
  public boolean getRequiresApproval() {
    return requiresApproval_;
  }

  public static final int APPROVAL_CONDITION_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object approvalCondition_ = "";
  /**
   * <pre>
   * 审批触发条件（JSON）
   * </pre>
   *
   * <code>string approval_condition = 9 [json_name = "approvalCondition"];</code>
   * @return The approvalCondition.
   */
  @java.lang.Override
  public java.lang.String getApprovalCondition() {
    java.lang.Object ref = approvalCondition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      approvalCondition_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 审批触发条件（JSON）
   * </pre>
   *
   * <code>string approval_condition = 9 [json_name = "approvalCondition"];</code>
   * @return The bytes for approvalCondition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApprovalConditionBytes() {
    java.lang.Object ref = approvalCondition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      approvalCondition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_DEPRECATED_FIELD_NUMBER = 10;
  private boolean isDeprecated_ = false;
  /**
   * <pre>
   * 是否已废弃
   * </pre>
   *
   * <code>bool is_deprecated = 10 [json_name = "isDeprecated"];</code>
   * @return The isDeprecated.
   */
  @java.lang.Override
  public boolean getIsDeprecated() {
    return isDeprecated_;
  }

  public static final int DEPRECATED_MESSAGE_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deprecatedMessage_ = "";
  /**
   * <pre>
   * 废弃提示
   * </pre>
   *
   * <code>string deprecated_message = 11 [json_name = "deprecatedMessage"];</code>
   * @return The deprecatedMessage.
   */
  @java.lang.Override
  public java.lang.String getDeprecatedMessage() {
    java.lang.Object ref = deprecatedMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deprecatedMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 废弃提示
   * </pre>
   *
   * <code>string deprecated_message = 11 [json_name = "deprecatedMessage"];</code>
   * @return The bytes for deprecatedMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeprecatedMessageBytes() {
    java.lang.Object ref = deprecatedMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deprecatedMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 12;
  private long createdAt_ = 0L;
  /**
   * <code>int64 created_at = 12 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 13;
  private long updatedAt_ = 0L;
  /**
   * <code>int64 updated_at = 13 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public long getUpdatedAt() {
    return updatedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, version_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, category_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(inputSchemaJson_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, inputSchemaJson_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputSchemaJson_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, outputSchemaJson_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(riskLevel_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, riskLevel_);
    }
    if (requiresApproval_ != false) {
      output.writeBool(8, requiresApproval_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(approvalCondition_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, approvalCondition_);
    }
    if (isDeprecated_ != false) {
      output.writeBool(10, isDeprecated_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deprecatedMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, deprecatedMessage_);
    }
    if (createdAt_ != 0L) {
      output.writeInt64(12, createdAt_);
    }
    if (updatedAt_ != 0L) {
      output.writeInt64(13, updatedAt_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, version_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, category_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(inputSchemaJson_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, inputSchemaJson_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputSchemaJson_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, outputSchemaJson_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(riskLevel_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, riskLevel_);
    }
    if (requiresApproval_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, requiresApproval_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(approvalCondition_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, approvalCondition_);
    }
    if (isDeprecated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isDeprecated_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deprecatedMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, deprecatedMessage_);
    }
    if (createdAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, createdAt_);
    }
    if (updatedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, updatedAt_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platform.toolbus.ToolInfo)) {
      return super.equals(obj);
    }
    com.platform.toolbus.ToolInfo other = (com.platform.toolbus.ToolInfo) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getCategory()
        .equals(other.getCategory())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getInputSchemaJson()
        .equals(other.getInputSchemaJson())) return false;
    if (!getOutputSchemaJson()
        .equals(other.getOutputSchemaJson())) return false;
    if (!getRiskLevel()
        .equals(other.getRiskLevel())) return false;
    if (getRequiresApproval()
        != other.getRequiresApproval()) return false;
    if (!getApprovalCondition()
        .equals(other.getApprovalCondition())) return false;
    if (getIsDeprecated()
        != other.getIsDeprecated()) return false;
    if (!getDeprecatedMessage()
        .equals(other.getDeprecatedMessage())) return false;
    if (getCreatedAt()
        != other.getCreatedAt()) return false;
    if (getUpdatedAt()
        != other.getUpdatedAt()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + INPUT_SCHEMA_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getInputSchemaJson().hashCode();
    hash = (37 * hash) + OUTPUT_SCHEMA_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getOutputSchemaJson().hashCode();
    hash = (37 * hash) + RISK_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getRiskLevel().hashCode();
    hash = (37 * hash) + REQUIRES_APPROVAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRequiresApproval());
    hash = (37 * hash) + APPROVAL_CONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getApprovalCondition().hashCode();
    hash = (37 * hash) + IS_DEPRECATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDeprecated());
    hash = (37 * hash) + DEPRECATED_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getDeprecatedMessage().hashCode();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAt());
    hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdatedAt());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platform.toolbus.ToolInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.platform.toolbus.ToolInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.platform.toolbus.ToolInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.platform.toolbus.ToolInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platform.toolbus.ToolInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ToolInfo - 工具信息
   * </pre>
   *
   * Protobuf type {@code toolbus.ToolInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:toolbus.ToolInfo)
      com.platform.toolbus.ToolInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platform.toolbus.ToolInfo.class, com.platform.toolbus.ToolInfo.Builder.class);
    }

    // Construct using com.platform.toolbus.ToolInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      version_ = "";
      category_ = "";
      description_ = "";
      inputSchemaJson_ = "";
      outputSchemaJson_ = "";
      riskLevel_ = "";
      requiresApproval_ = false;
      approvalCondition_ = "";
      isDeprecated_ = false;
      deprecatedMessage_ = "";
      createdAt_ = 0L;
      updatedAt_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platform.toolbus.ToolBus.internal_static_toolbus_ToolInfo_descriptor;
    }

    @java.lang.Override
    public com.platform.toolbus.ToolInfo getDefaultInstanceForType() {
      return com.platform.toolbus.ToolInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.platform.toolbus.ToolInfo build() {
      com.platform.toolbus.ToolInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platform.toolbus.ToolInfo buildPartial() {
      com.platform.toolbus.ToolInfo result = new com.platform.toolbus.ToolInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.platform.toolbus.ToolInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.category_ = category_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.inputSchemaJson_ = inputSchemaJson_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.outputSchemaJson_ = outputSchemaJson_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.riskLevel_ = riskLevel_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.requiresApproval_ = requiresApproval_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.approvalCondition_ = approvalCondition_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.isDeprecated_ = isDeprecated_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.deprecatedMessage_ = deprecatedMessage_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.createdAt_ = createdAt_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.updatedAt_ = updatedAt_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platform.toolbus.ToolInfo) {
        return mergeFrom((com.platform.toolbus.ToolInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platform.toolbus.ToolInfo other) {
      if (other == com.platform.toolbus.ToolInfo.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getInputSchemaJson().isEmpty()) {
        inputSchemaJson_ = other.inputSchemaJson_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getOutputSchemaJson().isEmpty()) {
        outputSchemaJson_ = other.outputSchemaJson_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getRiskLevel().isEmpty()) {
        riskLevel_ = other.riskLevel_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getRequiresApproval() != false) {
        setRequiresApproval(other.getRequiresApproval());
      }
      if (!other.getApprovalCondition().isEmpty()) {
        approvalCondition_ = other.approvalCondition_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getIsDeprecated() != false) {
        setIsDeprecated(other.getIsDeprecated());
      }
      if (!other.getDeprecatedMessage().isEmpty()) {
        deprecatedMessage_ = other.deprecatedMessage_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.getCreatedAt() != 0L) {
        setCreatedAt(other.getCreatedAt());
      }
      if (other.getUpdatedAt() != 0L) {
        setUpdatedAt(other.getUpdatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              category_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              inputSchemaJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              outputSchemaJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              riskLevel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              requiresApproval_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              approvalCondition_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              isDeprecated_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              deprecatedMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 96: {
              createdAt_ = input.readInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              updatedAt_ = input.readInt64();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 2 [json_name = "version"];</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 2 [json_name = "version"];</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 2 [json_name = "version"];</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2 [json_name = "version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2 [json_name = "version"];</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <pre>
     * query / write / external
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * query / write / external
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * query / write / external
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      category_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * query / write / external
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      category_ = getDefaultInstance().getCategory();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * query / write / external
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      category_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object inputSchemaJson_ = "";
    /**
     * <pre>
     * 输入 Schema（JSON）
     * </pre>
     *
     * <code>string input_schema_json = 5 [json_name = "inputSchemaJson"];</code>
     * @return The inputSchemaJson.
     */
    public java.lang.String getInputSchemaJson() {
      java.lang.Object ref = inputSchemaJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inputSchemaJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 输入 Schema（JSON）
     * </pre>
     *
     * <code>string input_schema_json = 5 [json_name = "inputSchemaJson"];</code>
     * @return The bytes for inputSchemaJson.
     */
    public com.google.protobuf.ByteString
        getInputSchemaJsonBytes() {
      java.lang.Object ref = inputSchemaJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inputSchemaJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 输入 Schema（JSON）
     * </pre>
     *
     * <code>string input_schema_json = 5 [json_name = "inputSchemaJson"];</code>
     * @param value The inputSchemaJson to set.
     * @return This builder for chaining.
     */
    public Builder setInputSchemaJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      inputSchemaJson_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输入 Schema（JSON）
     * </pre>
     *
     * <code>string input_schema_json = 5 [json_name = "inputSchemaJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInputSchemaJson() {
      inputSchemaJson_ = getDefaultInstance().getInputSchemaJson();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输入 Schema（JSON）
     * </pre>
     *
     * <code>string input_schema_json = 5 [json_name = "inputSchemaJson"];</code>
     * @param value The bytes for inputSchemaJson to set.
     * @return This builder for chaining.
     */
    public Builder setInputSchemaJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      inputSchemaJson_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object outputSchemaJson_ = "";
    /**
     * <pre>
     * 输出 Schema（JSON）
     * </pre>
     *
     * <code>string output_schema_json = 6 [json_name = "outputSchemaJson"];</code>
     * @return The outputSchemaJson.
     */
    public java.lang.String getOutputSchemaJson() {
      java.lang.Object ref = outputSchemaJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputSchemaJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 输出 Schema（JSON）
     * </pre>
     *
     * <code>string output_schema_json = 6 [json_name = "outputSchemaJson"];</code>
     * @return The bytes for outputSchemaJson.
     */
    public com.google.protobuf.ByteString
        getOutputSchemaJsonBytes() {
      java.lang.Object ref = outputSchemaJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputSchemaJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 输出 Schema（JSON）
     * </pre>
     *
     * <code>string output_schema_json = 6 [json_name = "outputSchemaJson"];</code>
     * @param value The outputSchemaJson to set.
     * @return This builder for chaining.
     */
    public Builder setOutputSchemaJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      outputSchemaJson_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输出 Schema（JSON）
     * </pre>
     *
     * <code>string output_schema_json = 6 [json_name = "outputSchemaJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputSchemaJson() {
      outputSchemaJson_ = getDefaultInstance().getOutputSchemaJson();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输出 Schema（JSON）
     * </pre>
     *
     * <code>string output_schema_json = 6 [json_name = "outputSchemaJson"];</code>
     * @param value The bytes for outputSchemaJson to set.
     * @return This builder for chaining.
     */
    public Builder setOutputSchemaJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      outputSchemaJson_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object riskLevel_ = "";
    /**
     * <pre>
     * 风险等级
     * </pre>
     *
     * <code>string risk_level = 7 [json_name = "riskLevel"];</code>
     * @return The riskLevel.
     */
    public java.lang.String getRiskLevel() {
      java.lang.Object ref = riskLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        riskLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 风险等级
     * </pre>
     *
     * <code>string risk_level = 7 [json_name = "riskLevel"];</code>
     * @return The bytes for riskLevel.
     */
    public com.google.protobuf.ByteString
        getRiskLevelBytes() {
      java.lang.Object ref = riskLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        riskLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 风险等级
     * </pre>
     *
     * <code>string risk_level = 7 [json_name = "riskLevel"];</code>
     * @param value The riskLevel to set.
     * @return This builder for chaining.
     */
    public Builder setRiskLevel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      riskLevel_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 风险等级
     * </pre>
     *
     * <code>string risk_level = 7 [json_name = "riskLevel"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRiskLevel() {
      riskLevel_ = getDefaultInstance().getRiskLevel();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 风险等级
     * </pre>
     *
     * <code>string risk_level = 7 [json_name = "riskLevel"];</code>
     * @param value The bytes for riskLevel to set.
     * @return This builder for chaining.
     */
    public Builder setRiskLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      riskLevel_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private boolean requiresApproval_ ;
    /**
     * <pre>
     * 是否需要审批
     * </pre>
     *
     * <code>bool requires_approval = 8 [json_name = "requiresApproval"];</code>
     * @return The requiresApproval.
     */
    @java.lang.Override
    public boolean getRequiresApproval() {
      return requiresApproval_;
    }
    /**
     * <pre>
     * 是否需要审批
     * </pre>
     *
     * <code>bool requires_approval = 8 [json_name = "requiresApproval"];</code>
     * @param value The requiresApproval to set.
     * @return This builder for chaining.
     */
    public Builder setRequiresApproval(boolean value) {

      requiresApproval_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否需要审批
     * </pre>
     *
     * <code>bool requires_approval = 8 [json_name = "requiresApproval"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequiresApproval() {
      bitField0_ = (bitField0_ & ~0x00000080);
      requiresApproval_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object approvalCondition_ = "";
    /**
     * <pre>
     * 审批触发条件（JSON）
     * </pre>
     *
     * <code>string approval_condition = 9 [json_name = "approvalCondition"];</code>
     * @return The approvalCondition.
     */
    public java.lang.String getApprovalCondition() {
      java.lang.Object ref = approvalCondition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        approvalCondition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 审批触发条件（JSON）
     * </pre>
     *
     * <code>string approval_condition = 9 [json_name = "approvalCondition"];</code>
     * @return The bytes for approvalCondition.
     */
    public com.google.protobuf.ByteString
        getApprovalConditionBytes() {
      java.lang.Object ref = approvalCondition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        approvalCondition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 审批触发条件（JSON）
     * </pre>
     *
     * <code>string approval_condition = 9 [json_name = "approvalCondition"];</code>
     * @param value The approvalCondition to set.
     * @return This builder for chaining.
     */
    public Builder setApprovalCondition(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      approvalCondition_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 审批触发条件（JSON）
     * </pre>
     *
     * <code>string approval_condition = 9 [json_name = "approvalCondition"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApprovalCondition() {
      approvalCondition_ = getDefaultInstance().getApprovalCondition();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 审批触发条件（JSON）
     * </pre>
     *
     * <code>string approval_condition = 9 [json_name = "approvalCondition"];</code>
     * @param value The bytes for approvalCondition to set.
     * @return This builder for chaining.
     */
    public Builder setApprovalConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      approvalCondition_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private boolean isDeprecated_ ;
    /**
     * <pre>
     * 是否已废弃
     * </pre>
     *
     * <code>bool is_deprecated = 10 [json_name = "isDeprecated"];</code>
     * @return The isDeprecated.
     */
    @java.lang.Override
    public boolean getIsDeprecated() {
      return isDeprecated_;
    }
    /**
     * <pre>
     * 是否已废弃
     * </pre>
     *
     * <code>bool is_deprecated = 10 [json_name = "isDeprecated"];</code>
     * @param value The isDeprecated to set.
     * @return This builder for chaining.
     */
    public Builder setIsDeprecated(boolean value) {

      isDeprecated_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否已废弃
     * </pre>
     *
     * <code>bool is_deprecated = 10 [json_name = "isDeprecated"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDeprecated() {
      bitField0_ = (bitField0_ & ~0x00000200);
      isDeprecated_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object deprecatedMessage_ = "";
    /**
     * <pre>
     * 废弃提示
     * </pre>
     *
     * <code>string deprecated_message = 11 [json_name = "deprecatedMessage"];</code>
     * @return The deprecatedMessage.
     */
    public java.lang.String getDeprecatedMessage() {
      java.lang.Object ref = deprecatedMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deprecatedMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 废弃提示
     * </pre>
     *
     * <code>string deprecated_message = 11 [json_name = "deprecatedMessage"];</code>
     * @return The bytes for deprecatedMessage.
     */
    public com.google.protobuf.ByteString
        getDeprecatedMessageBytes() {
      java.lang.Object ref = deprecatedMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deprecatedMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 废弃提示
     * </pre>
     *
     * <code>string deprecated_message = 11 [json_name = "deprecatedMessage"];</code>
     * @param value The deprecatedMessage to set.
     * @return This builder for chaining.
     */
    public Builder setDeprecatedMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deprecatedMessage_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 废弃提示
     * </pre>
     *
     * <code>string deprecated_message = 11 [json_name = "deprecatedMessage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeprecatedMessage() {
      deprecatedMessage_ = getDefaultInstance().getDeprecatedMessage();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 废弃提示
     * </pre>
     *
     * <code>string deprecated_message = 11 [json_name = "deprecatedMessage"];</code>
     * @param value The bytes for deprecatedMessage to set.
     * @return This builder for chaining.
     */
    public Builder setDeprecatedMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deprecatedMessage_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <code>int64 created_at = 12 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>int64 created_at = 12 [json_name = "createdAt"];</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {

      createdAt_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int64 created_at = 12 [json_name = "createdAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000800);
      createdAt_ = 0L;
      onChanged();
      return this;
    }

    private long updatedAt_ ;
    /**
     * <code>int64 updated_at = 13 [json_name = "updatedAt"];</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>int64 updated_at = 13 [json_name = "updatedAt"];</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(long value) {

      updatedAt_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>int64 updated_at = 13 [json_name = "updatedAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00001000);
      updatedAt_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:toolbus.ToolInfo)
  }

  // @@protoc_insertion_point(class_scope:toolbus.ToolInfo)
  private static final com.platform.toolbus.ToolInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platform.toolbus.ToolInfo();
  }

  public static com.platform.toolbus.ToolInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ToolInfo>
      PARSER = new com.google.protobuf.AbstractParser<ToolInfo>() {
    @java.lang.Override
    public ToolInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ToolInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ToolInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platform.toolbus.ToolInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

