// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: toolbus/tool_bus.proto
// Protobuf Java Version: 4.35.1

package com.platform.toolbus;

@com.google.protobuf.Generated
public interface ToolsBatchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:toolbus.ToolsBatchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.toolbus.RequestContext getContext();
  /**
   * <code>.toolbus.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.toolbus.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <pre>
   * 结果列表
   * </pre>
   *
   * <code>repeated .toolbus.ToolExecuteResponse results = 2 [json_name = "results"];</code>
   */
  java.util.List<com.platform.toolbus.ToolExecuteResponse> 
      getResultsList();
  /**
   * <pre>
   * 结果列表
   * </pre>
   *
   * <code>repeated .toolbus.ToolExecuteResponse results = 2 [json_name = "results"];</code>
   */
  com.platform.toolbus.ToolExecuteResponse getResults(int index);
  /**
   * <pre>
   * 结果列表
   * </pre>
   *
   * <code>repeated .toolbus.ToolExecuteResponse results = 2 [json_name = "results"];</code>
   */
  int getResultsCount();
  /**
   * <pre>
   * 结果列表
   * </pre>
   *
   * <code>repeated .toolbus.ToolExecuteResponse results = 2 [json_name = "results"];</code>
   */
  java.util.List<? extends com.platform.toolbus.ToolExecuteResponseOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <pre>
   * 结果列表
   * </pre>
   *
   * <code>repeated .toolbus.ToolExecuteResponse results = 2 [json_name = "results"];</code>
   */
  com.platform.toolbus.ToolExecuteResponseOrBuilder getResultsOrBuilder(
      int index);

  /**
   * <pre>
   * 总耗时
   * </pre>
   *
   * <code>int32 total_duration_ms = 3 [json_name = "totalDurationMs"];</code>
   * @return The totalDurationMs.
   */
  int getTotalDurationMs();
}
