// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gateway/orchestrator.proto
// Protobuf Java Version: 4.35.1

package com.platform.gateway;

@com.google.protobuf.Generated
public interface AgentStepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.AgentStep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string step_id = 1 [json_name = "stepId"];</code>
   * @return The stepId.
   */
  java.lang.String getStepId();
  /**
   * <code>string step_id = 1 [json_name = "stepId"];</code>
   * @return The bytes for stepId.
   */
  com.google.protobuf.ByteString
      getStepIdBytes();

  /**
   * <code>int32 step_order = 2 [json_name = "stepOrder"];</code>
   * @return The stepOrder.
   */
  int getStepOrder();

  /**
   * <pre>
   * thinking / tool_call / observation / final_answer
   * </pre>
   *
   * <code>string step_type = 3 [json_name = "stepType"];</code>
   * @return The stepType.
   */
  java.lang.String getStepType();
  /**
   * <pre>
   * thinking / tool_call / observation / final_answer
   * </pre>
   *
   * <code>string step_type = 3 [json_name = "stepType"];</code>
   * @return The bytes for stepType.
   */
  com.google.protobuf.ByteString
      getStepTypeBytes();

  /**
   * <pre>
   * 步骤内容
   * </pre>
   *
   * <code>string content = 4 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 步骤内容
   * </pre>
   *
   * <code>string content = 4 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * CoT 思考过程
   * </pre>
   *
   * <code>string thinking = 5 [json_name = "thinking"];</code>
   * @return The thinking.
   */
  java.lang.String getThinking();
  /**
   * <pre>
   * CoT 思考过程
   * </pre>
   *
   * <code>string thinking = 5 [json_name = "thinking"];</code>
   * @return The bytes for thinking.
   */
  com.google.protobuf.ByteString
      getThinkingBytes();

  /**
   * <pre>
   * 工具调用详情
   * </pre>
   *
   * <code>.gateway.ToolCall tool_call = 6 [json_name = "toolCall"];</code>
   * @return Whether the toolCall field is set.
   */
  boolean hasToolCall();
  /**
   * <pre>
   * 工具调用详情
   * </pre>
   *
   * <code>.gateway.ToolCall tool_call = 6 [json_name = "toolCall"];</code>
   * @return The toolCall.
   */
  com.platform.gateway.ToolCall getToolCall();
  /**
   * <pre>
   * 工具调用详情
   * </pre>
   *
   * <code>.gateway.ToolCall tool_call = 6 [json_name = "toolCall"];</code>
   */
  com.platform.gateway.ToolCallOrBuilder getToolCallOrBuilder();

  /**
   * <code>.gateway.ToolResult tool_result = 7 [json_name = "toolResult"];</code>
   * @return Whether the toolResult field is set.
   */
  boolean hasToolResult();
  /**
   * <code>.gateway.ToolResult tool_result = 7 [json_name = "toolResult"];</code>
   * @return The toolResult.
   */
  com.platform.gateway.ToolResult getToolResult();
  /**
   * <code>.gateway.ToolResult tool_result = 7 [json_name = "toolResult"];</code>
   */
  com.platform.gateway.ToolResultOrBuilder getToolResultOrBuilder();

  /**
   * <code>int64 created_at = 8 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <code>int32 duration_ms = 9 [json_name = "durationMs"];</code>
   * @return The durationMs.
   */
  int getDurationMs();
}
