// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gateway/orchestrator.proto
// Protobuf Java Version: 4.35.1

package com.platform.gateway;

@com.google.protobuf.Generated
public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.gateway.RequestContext getContext();
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.gateway.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <pre>
   * AI 响应内容
   * </pre>
   *
   * <code>string response = 2 [json_name = "response"];</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <pre>
   * AI 响应内容
   * </pre>
   *
   * <code>string response = 2 [json_name = "response"];</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();

  /**
   * <pre>
   * 实际使用的模型
   * </pre>
   *
   * <code>string model_used = 3 [json_name = "modelUsed"];</code>
   * @return The modelUsed.
   */
  java.lang.String getModelUsed();
  /**
   * <pre>
   * 实际使用的模型
   * </pre>
   *
   * <code>string model_used = 3 [json_name = "modelUsed"];</code>
   * @return The bytes for modelUsed.
   */
  com.google.protobuf.ByteString
      getModelUsedBytes();

  /**
   * <pre>
   * 输入 token 数
   * </pre>
   *
   * <code>int32 prompt_tokens = 4 [json_name = "promptTokens"];</code>
   * @return The promptTokens.
   */
  int getPromptTokens();

  /**
   * <pre>
   * 输出 token 数
   * </pre>
   *
   * <code>int32 completion_tokens = 5 [json_name = "completionTokens"];</code>
   * @return The completionTokens.
   */
  int getCompletionTokens();

  /**
   * <pre>
   * 总 token 数
   * </pre>
   *
   * <code>int32 total_tokens = 6 [json_name = "totalTokens"];</code>
   * @return The totalTokens.
   */
  int getTotalTokens();

  /**
   * <pre>
   * 成本（美元）
   * </pre>
   *
   * <code>float cost_usd = 7 [json_name = "costUsd"];</code>
   * @return The costUsd.
   */
  float getCostUsd();

  /**
   * <pre>
   * 工具调用信息
   * </pre>
   *
   * <code>repeated .gateway.ToolCall tool_calls = 8 [json_name = "toolCalls"];</code>
   */
  java.util.List<com.platform.gateway.ToolCall> 
      getToolCallsList();
  /**
   * <pre>
   * 工具调用信息
   * </pre>
   *
   * <code>repeated .gateway.ToolCall tool_calls = 8 [json_name = "toolCalls"];</code>
   */
  com.platform.gateway.ToolCall getToolCalls(int index);
  /**
   * <pre>
   * 工具调用信息
   * </pre>
   *
   * <code>repeated .gateway.ToolCall tool_calls = 8 [json_name = "toolCalls"];</code>
   */
  int getToolCallsCount();
  /**
   * <pre>
   * 工具调用信息
   * </pre>
   *
   * <code>repeated .gateway.ToolCall tool_calls = 8 [json_name = "toolCalls"];</code>
   */
  java.util.List<? extends com.platform.gateway.ToolCallOrBuilder> 
      getToolCallsOrBuilderList();
  /**
   * <pre>
   * 工具调用信息
   * </pre>
   *
   * <code>repeated .gateway.ToolCall tool_calls = 8 [json_name = "toolCalls"];</code>
   */
  com.platform.gateway.ToolCallOrBuilder getToolCallsOrBuilder(
      int index);

  /**
   * <pre>
   * 元信息
   * </pre>
   *
   * <code>int64 created_at = 9 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <pre>
   * 耗时（毫秒）
   * </pre>
   *
   * <code>int32 latency_ms = 10 [json_name = "latencyMs"];</code>
   * @return The latencyMs.
   */
  int getLatencyMs();

  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>string finish_reason = 11 [json_name = "finishReason"];</code>
   * @return The finishReason.
   */
  java.lang.String getFinishReason();
  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>string finish_reason = 11 [json_name = "finishReason"];</code>
   * @return The bytes for finishReason.
   */
  com.google.protobuf.ByteString
      getFinishReasonBytes();

  /**
   * <pre>
   * 错误信息（如有）
   * </pre>
   *
   * <code>.common.ErrorDetail error = 12 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * 错误信息（如有）
   * </pre>
   *
   * <code>.common.ErrorDetail error = 12 [json_name = "error"];</code>
   * @return The error.
   */
  com.platform.common.ErrorDetail getError();
  /**
   * <pre>
   * 错误信息（如有）
   * </pre>
   *
   * <code>.common.ErrorDetail error = 12 [json_name = "error"];</code>
   */
  com.platform.common.ErrorDetailOrBuilder getErrorOrBuilder();
}
