// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gateway/orchestrator.proto
// Protobuf Java Version: 4.35.1

package com.platform.gateway;

/**
 * <pre>
 * ChatStreamChunk - 流式响应块
 * </pre>
 *
 * Protobuf type {@code gateway.ChatStreamChunk}
 */
@com.google.protobuf.Generated
public final class ChatStreamChunk extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:gateway.ChatStreamChunk)
    ChatStreamChunkOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ChatStreamChunk");
  }
  // Use ChatStreamChunk.newBuilder() to construct.
  private ChatStreamChunk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChatStreamChunk() {
    chunkId_ = "";
    delta_ = "";
    finishReason_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platform.gateway.Orchestrator.internal_static_gateway_ChatStreamChunk_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.platform.gateway.Orchestrator.internal_static_gateway_ChatStreamChunk_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platform.gateway.Orchestrator.internal_static_gateway_ChatStreamChunk_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platform.gateway.ChatStreamChunk.class, com.platform.gateway.ChatStreamChunk.Builder.class);
  }

  private int bitField0_;
  public static final int CONTEXT_FIELD_NUMBER = 1;
  private com.platform.gateway.RequestContext context_;
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  @java.lang.Override
  public boolean hasContext() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  @java.lang.Override
  public com.platform.gateway.RequestContext getContext() {
    return context_ == null ? com.platform.gateway.RequestContext.getDefaultInstance() : context_;
  }
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   */
  @java.lang.Override
  public com.platform.gateway.RequestContextOrBuilder getContextOrBuilder() {
    return context_ == null ? com.platform.gateway.RequestContext.getDefaultInstance() : context_;
  }

  public static final int CHUNK_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object chunkId_ = "";
  /**
   * <pre>
   * 响应块 ID
   * </pre>
   *
   * <code>string chunk_id = 2 [json_name = "chunkId"];</code>
   * @return The chunkId.
   */
  @java.lang.Override
  public java.lang.String getChunkId() {
    java.lang.Object ref = chunkId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chunkId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 响应块 ID
   * </pre>
   *
   * <code>string chunk_id = 2 [json_name = "chunkId"];</code>
   * @return The bytes for chunkId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChunkIdBytes() {
    java.lang.Object ref = chunkId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chunkId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHUNK_INDEX_FIELD_NUMBER = 3;
  private int chunkIndex_ = 0;
  /**
   * <pre>
   * 响应块序号
   * </pre>
   *
   * <code>int32 chunk_index = 3 [json_name = "chunkIndex"];</code>
   * @return The chunkIndex.
   */
  @java.lang.Override
  public int getChunkIndex() {
    return chunkIndex_;
  }

  public static final int DELTA_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object delta_ = "";
  /**
   * <pre>
   * 响应增量内容
   * </pre>
   *
   * <code>string delta = 4 [json_name = "delta"];</code>
   * @return The delta.
   */
  @java.lang.Override
  public java.lang.String getDelta() {
    java.lang.Object ref = delta_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      delta_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 响应增量内容
   * </pre>
   *
   * <code>string delta = 4 [json_name = "delta"];</code>
   * @return The bytes for delta.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeltaBytes() {
    java.lang.Object ref = delta_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      delta_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FINISH_REASON_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object finishReason_ = "";
  /**
   * <pre>
   * 完成原因（最后一个块）
   * </pre>
   *
   * <code>string finish_reason = 5 [json_name = "finishReason"];</code>
   * @return The finishReason.
   */
  @java.lang.Override
  public java.lang.String getFinishReason() {
    java.lang.Object ref = finishReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      finishReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 完成原因（最后一个块）
   * </pre>
   *
   * <code>string finish_reason = 5 [json_name = "finishReason"];</code>
   * @return The bytes for finishReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFinishReasonBytes() {
    java.lang.Object ref = finishReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      finishReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 6;
  private com.platform.common.ErrorDetail error_;
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public com.platform.common.ErrorDetail getError() {
    return error_ == null ? com.platform.common.ErrorDetail.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
   */
  @java.lang.Override
  public com.platform.common.ErrorDetailOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.platform.common.ErrorDetail.getDefaultInstance() : error_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getContext());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(chunkId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, chunkId_);
    }
    if (chunkIndex_ != 0) {
      output.writeInt32(3, chunkIndex_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(delta_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, delta_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(finishReason_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, finishReason_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getError());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContext());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(chunkId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, chunkId_);
    }
    if (chunkIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, chunkIndex_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(delta_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, delta_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(finishReason_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, finishReason_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getError());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platform.gateway.ChatStreamChunk)) {
      return super.equals(obj);
    }
    com.platform.gateway.ChatStreamChunk other = (com.platform.gateway.ChatStreamChunk) obj;

    if (hasContext() != other.hasContext()) return false;
    if (hasContext()) {
      if (!getContext()
          .equals(other.getContext())) return false;
    }
    if (!getChunkId()
        .equals(other.getChunkId())) return false;
    if (getChunkIndex()
        != other.getChunkIndex()) return false;
    if (!getDelta()
        .equals(other.getDelta())) return false;
    if (!getFinishReason()
        .equals(other.getFinishReason())) return false;
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContext()) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
    }
    hash = (37 * hash) + CHUNK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChunkId().hashCode();
    hash = (37 * hash) + CHUNK_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getChunkIndex();
    hash = (37 * hash) + DELTA_FIELD_NUMBER;
    hash = (53 * hash) + getDelta().hashCode();
    hash = (37 * hash) + FINISH_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getFinishReason().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platform.gateway.ChatStreamChunk parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.platform.gateway.ChatStreamChunk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.platform.gateway.ChatStreamChunk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.platform.gateway.ChatStreamChunk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platform.gateway.ChatStreamChunk prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ChatStreamChunk - 流式响应块
   * </pre>
   *
   * Protobuf type {@code gateway.ChatStreamChunk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gateway.ChatStreamChunk)
      com.platform.gateway.ChatStreamChunkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platform.gateway.Orchestrator.internal_static_gateway_ChatStreamChunk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platform.gateway.Orchestrator.internal_static_gateway_ChatStreamChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platform.gateway.ChatStreamChunk.class, com.platform.gateway.ChatStreamChunk.Builder.class);
    }

    // Construct using com.platform.gateway.ChatStreamChunk.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetContextFieldBuilder();
        internalGetErrorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      chunkId_ = "";
      chunkIndex_ = 0;
      delta_ = "";
      finishReason_ = "";
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platform.gateway.Orchestrator.internal_static_gateway_ChatStreamChunk_descriptor;
    }

    @java.lang.Override
    public com.platform.gateway.ChatStreamChunk getDefaultInstanceForType() {
      return com.platform.gateway.ChatStreamChunk.getDefaultInstance();
    }

    @java.lang.Override
    public com.platform.gateway.ChatStreamChunk build() {
      com.platform.gateway.ChatStreamChunk result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platform.gateway.ChatStreamChunk buildPartial() {
      com.platform.gateway.ChatStreamChunk result = new com.platform.gateway.ChatStreamChunk(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.platform.gateway.ChatStreamChunk result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.context_ = contextBuilder_ == null
            ? context_
            : contextBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.chunkId_ = chunkId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.chunkIndex_ = chunkIndex_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.delta_ = delta_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.finishReason_ = finishReason_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platform.gateway.ChatStreamChunk) {
        return mergeFrom((com.platform.gateway.ChatStreamChunk)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platform.gateway.ChatStreamChunk other) {
      if (other == com.platform.gateway.ChatStreamChunk.getDefaultInstance()) return this;
      if (other.hasContext()) {
        mergeContext(other.getContext());
      }
      if (!other.getChunkId().isEmpty()) {
        chunkId_ = other.chunkId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getChunkIndex() != 0) {
        setChunkIndex(other.getChunkIndex());
      }
      if (!other.getDelta().isEmpty()) {
        delta_ = other.delta_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getFinishReason().isEmpty()) {
        finishReason_ = other.finishReason_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetContextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              chunkId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              chunkIndex_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              delta_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              finishReason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.platform.gateway.RequestContext context_;
    private com.google.protobuf.SingleFieldBuilder<
        com.platform.gateway.RequestContext, com.platform.gateway.RequestContext.Builder, com.platform.gateway.RequestContextOrBuilder> contextBuilder_;
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     * @return Whether the context field is set.
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     * @return The context.
     */
    public com.platform.gateway.RequestContext getContext() {
      if (contextBuilder_ == null) {
        return context_ == null ? com.platform.gateway.RequestContext.getDefaultInstance() : context_;
      } else {
        return contextBuilder_.getMessage();
      }
    }
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder setContext(com.platform.gateway.RequestContext value) {
      if (contextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        context_ = value;
      } else {
        contextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder setContext(
        com.platform.gateway.RequestContext.Builder builderForValue) {
      if (contextBuilder_ == null) {
        context_ = builderForValue.build();
      } else {
        contextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder mergeContext(com.platform.gateway.RequestContext value) {
      if (contextBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          context_ != null &&
          context_ != com.platform.gateway.RequestContext.getDefaultInstance()) {
          getContextBuilder().mergeFrom(value);
        } else {
          context_ = value;
        }
      } else {
        contextBuilder_.mergeFrom(value);
      }
      if (context_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder clearContext() {
      bitField0_ = (bitField0_ & ~0x00000001);
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     */
    public com.platform.gateway.RequestContext.Builder getContextBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     */
    public com.platform.gateway.RequestContextOrBuilder getContextOrBuilder() {
      if (contextBuilder_ != null) {
        return contextBuilder_.getMessageOrBuilder();
      } else {
        return context_ == null ?
            com.platform.gateway.RequestContext.getDefaultInstance() : context_;
      }
    }
    /**
     * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.platform.gateway.RequestContext, com.platform.gateway.RequestContext.Builder, com.platform.gateway.RequestContextOrBuilder> 
        internalGetContextFieldBuilder() {
      if (contextBuilder_ == null) {
        contextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.platform.gateway.RequestContext, com.platform.gateway.RequestContext.Builder, com.platform.gateway.RequestContextOrBuilder>(
                getContext(),
                getParentForChildren(),
                isClean());
        context_ = null;
      }
      return contextBuilder_;
    }

    private java.lang.Object chunkId_ = "";
    /**
     * <pre>
     * 响应块 ID
     * </pre>
     *
     * <code>string chunk_id = 2 [json_name = "chunkId"];</code>
     * @return The chunkId.
     */
    public java.lang.String getChunkId() {
      java.lang.Object ref = chunkId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chunkId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 响应块 ID
     * </pre>
     *
     * <code>string chunk_id = 2 [json_name = "chunkId"];</code>
     * @return The bytes for chunkId.
     */
    public com.google.protobuf.ByteString
        getChunkIdBytes() {
      java.lang.Object ref = chunkId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chunkId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 响应块 ID
     * </pre>
     *
     * <code>string chunk_id = 2 [json_name = "chunkId"];</code>
     * @param value The chunkId to set.
     * @return This builder for chaining.
     */
    public Builder setChunkId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      chunkId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应块 ID
     * </pre>
     *
     * <code>string chunk_id = 2 [json_name = "chunkId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChunkId() {
      chunkId_ = getDefaultInstance().getChunkId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应块 ID
     * </pre>
     *
     * <code>string chunk_id = 2 [json_name = "chunkId"];</code>
     * @param value The bytes for chunkId to set.
     * @return This builder for chaining.
     */
    public Builder setChunkIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      chunkId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int chunkIndex_ ;
    /**
     * <pre>
     * 响应块序号
     * </pre>
     *
     * <code>int32 chunk_index = 3 [json_name = "chunkIndex"];</code>
     * @return The chunkIndex.
     */
    @java.lang.Override
    public int getChunkIndex() {
      return chunkIndex_;
    }
    /**
     * <pre>
     * 响应块序号
     * </pre>
     *
     * <code>int32 chunk_index = 3 [json_name = "chunkIndex"];</code>
     * @param value The chunkIndex to set.
     * @return This builder for chaining.
     */
    public Builder setChunkIndex(int value) {

      chunkIndex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应块序号
     * </pre>
     *
     * <code>int32 chunk_index = 3 [json_name = "chunkIndex"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChunkIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      chunkIndex_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object delta_ = "";
    /**
     * <pre>
     * 响应增量内容
     * </pre>
     *
     * <code>string delta = 4 [json_name = "delta"];</code>
     * @return The delta.
     */
    public java.lang.String getDelta() {
      java.lang.Object ref = delta_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        delta_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 响应增量内容
     * </pre>
     *
     * <code>string delta = 4 [json_name = "delta"];</code>
     * @return The bytes for delta.
     */
    public com.google.protobuf.ByteString
        getDeltaBytes() {
      java.lang.Object ref = delta_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        delta_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 响应增量内容
     * </pre>
     *
     * <code>string delta = 4 [json_name = "delta"];</code>
     * @param value The delta to set.
     * @return This builder for chaining.
     */
    public Builder setDelta(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      delta_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应增量内容
     * </pre>
     *
     * <code>string delta = 4 [json_name = "delta"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDelta() {
      delta_ = getDefaultInstance().getDelta();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应增量内容
     * </pre>
     *
     * <code>string delta = 4 [json_name = "delta"];</code>
     * @param value The bytes for delta to set.
     * @return This builder for chaining.
     */
    public Builder setDeltaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      delta_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object finishReason_ = "";
    /**
     * <pre>
     * 完成原因（最后一个块）
     * </pre>
     *
     * <code>string finish_reason = 5 [json_name = "finishReason"];</code>
     * @return The finishReason.
     */
    public java.lang.String getFinishReason() {
      java.lang.Object ref = finishReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        finishReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 完成原因（最后一个块）
     * </pre>
     *
     * <code>string finish_reason = 5 [json_name = "finishReason"];</code>
     * @return The bytes for finishReason.
     */
    public com.google.protobuf.ByteString
        getFinishReasonBytes() {
      java.lang.Object ref = finishReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        finishReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 完成原因（最后一个块）
     * </pre>
     *
     * <code>string finish_reason = 5 [json_name = "finishReason"];</code>
     * @param value The finishReason to set.
     * @return This builder for chaining.
     */
    public Builder setFinishReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      finishReason_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 完成原因（最后一个块）
     * </pre>
     *
     * <code>string finish_reason = 5 [json_name = "finishReason"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFinishReason() {
      finishReason_ = getDefaultInstance().getFinishReason();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 完成原因（最后一个块）
     * </pre>
     *
     * <code>string finish_reason = 5 [json_name = "finishReason"];</code>
     * @param value The bytes for finishReason to set.
     * @return This builder for chaining.
     */
    public Builder setFinishReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      finishReason_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.platform.common.ErrorDetail error_;
    private com.google.protobuf.SingleFieldBuilder<
        com.platform.common.ErrorDetail, com.platform.common.ErrorDetail.Builder, com.platform.common.ErrorDetailOrBuilder> errorBuilder_;
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     * @return The error.
     */
    public com.platform.common.ErrorDetail getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.platform.common.ErrorDetail.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     */
    public Builder setError(com.platform.common.ErrorDetail value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     */
    public Builder setError(
        com.platform.common.ErrorDetail.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     */
    public Builder mergeError(com.platform.common.ErrorDetail value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          error_ != null &&
          error_ != com.platform.common.ErrorDetail.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      if (error_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000020);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     */
    public com.platform.common.ErrorDetail.Builder getErrorBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     */
    public com.platform.common.ErrorDetailOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.platform.common.ErrorDetail.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>.common.ErrorDetail error = 6 [json_name = "error"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.platform.common.ErrorDetail, com.platform.common.ErrorDetail.Builder, com.platform.common.ErrorDetailOrBuilder> 
        internalGetErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.platform.common.ErrorDetail, com.platform.common.ErrorDetail.Builder, com.platform.common.ErrorDetailOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:gateway.ChatStreamChunk)
  }

  // @@protoc_insertion_point(class_scope:gateway.ChatStreamChunk)
  private static final com.platform.gateway.ChatStreamChunk DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platform.gateway.ChatStreamChunk();
  }

  public static com.platform.gateway.ChatStreamChunk getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatStreamChunk>
      PARSER = new com.google.protobuf.AbstractParser<ChatStreamChunk>() {
    @java.lang.Override
    public ChatStreamChunk parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatStreamChunk> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatStreamChunk> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platform.gateway.ChatStreamChunk getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

