// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gateway/orchestrator.proto
// Protobuf Java Version: 4.35.1

package com.platform.gateway;

@com.google.protobuf.Generated
public interface ChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.ChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.gateway.RequestContext getContext();
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.gateway.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated .gateway.Message history = 3 [json_name = "history"];</code>
   */
  java.util.List<com.platform.gateway.Message> 
      getHistoryList();
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated .gateway.Message history = 3 [json_name = "history"];</code>
   */
  com.platform.gateway.Message getHistory(int index);
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated .gateway.Message history = 3 [json_name = "history"];</code>
   */
  int getHistoryCount();
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated .gateway.Message history = 3 [json_name = "history"];</code>
   */
  java.util.List<? extends com.platform.gateway.MessageOrBuilder> 
      getHistoryOrBuilderList();
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated .gateway.Message history = 3 [json_name = "history"];</code>
   */
  com.platform.gateway.MessageOrBuilder getHistoryOrBuilder(
      int index);

  /**
   * <pre>
   * 配置
   * </pre>
   *
   * <code>string model = 4 [json_name = "model"];</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <pre>
   * 配置
   * </pre>
   *
   * <code>string model = 4 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <pre>
   * 温度参数
   * </pre>
   *
   * <code>float temperature = 5 [json_name = "temperature"];</code>
   * @return The temperature.
   */
  float getTemperature();

  /**
   * <pre>
   * 最大 token 数
   * </pre>
   *
   * <code>int32 max_tokens = 6 [json_name = "maxTokens"];</code>
   * @return The maxTokens.
   */
  int getMaxTokens();

  /**
   * <pre>
   * 停止词
   * </pre>
   *
   * <code>repeated string stop = 7 [json_name = "stop"];</code>
   * @return A list containing the stop.
   */
  java.util.List<java.lang.String>
      getStopList();
  /**
   * <pre>
   * 停止词
   * </pre>
   *
   * <code>repeated string stop = 7 [json_name = "stop"];</code>
   * @return The count of stop.
   */
  int getStopCount();
  /**
   * <pre>
   * 停止词
   * </pre>
   *
   * <code>repeated string stop = 7 [json_name = "stop"];</code>
   * @param index The index of the element to return.
   * @return The stop at the given index.
   */
  java.lang.String getStop(int index);
  /**
   * <pre>
   * 停止词
   * </pre>
   *
   * <code>repeated string stop = 7 [json_name = "stop"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the stop at the given index.
   */
  com.google.protobuf.ByteString
      getStopBytes(int index);

  /**
   * <pre>
   * 功能开关
   * </pre>
   *
   * <code>bool enable_rag = 8 [json_name = "enableRag"];</code>
   * @return The enableRag.
   */
  boolean getEnableRag();

  /**
   * <pre>
   * 是否启用工具
   * </pre>
   *
   * <code>bool enable_tools = 9 [json_name = "enableTools"];</code>
   * @return The enableTools.
   */
  boolean getEnableTools();

  /**
   * <pre>
   * 工具白名单
   * </pre>
   *
   * <code>repeated string tool_whitelist = 10 [json_name = "toolWhitelist"];</code>
   * @return A list containing the toolWhitelist.
   */
  java.util.List<java.lang.String>
      getToolWhitelistList();
  /**
   * <pre>
   * 工具白名单
   * </pre>
   *
   * <code>repeated string tool_whitelist = 10 [json_name = "toolWhitelist"];</code>
   * @return The count of toolWhitelist.
   */
  int getToolWhitelistCount();
  /**
   * <pre>
   * 工具白名单
   * </pre>
   *
   * <code>repeated string tool_whitelist = 10 [json_name = "toolWhitelist"];</code>
   * @param index The index of the element to return.
   * @return The toolWhitelist at the given index.
   */
  java.lang.String getToolWhitelist(int index);
  /**
   * <pre>
   * 工具白名单
   * </pre>
   *
   * <code>repeated string tool_whitelist = 10 [json_name = "toolWhitelist"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the toolWhitelist at the given index.
   */
  com.google.protobuf.ByteString
      getToolWhitelistBytes(int index);

  /**
   * <pre>
   * 流式控制
   * </pre>
   *
   * <code>bool stream = 11 [json_name = "stream"];</code>
   * @return The stream.
   */
  boolean getStream();
}
