// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gateway/orchestrator.proto
// Protobuf Java Version: 4.35.1

package com.platform.gateway;

@com.google.protobuf.Generated
public interface GetRunStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.GetRunStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.gateway.RequestContext getContext();
  /**
   * <code>.gateway.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.gateway.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <code>string run_id = 2 [json_name = "runId"];</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 2 [json_name = "runId"];</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();
}
