// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gateway/orchestrator.proto
// Protobuf Java Version: 4.35.1

package com.platform.gateway;

@com.google.protobuf.Generated
public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * user / assistant / system
   * </pre>
   *
   * <code>string role = 1 [json_name = "role"];</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <pre>
   * user / assistant / system
   * </pre>
   *
   * <code>string role = 1 [json_name = "role"];</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 名称（可选）
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 名称（可选）
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
