// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gateway/orchestrator.proto
// Protobuf Java Version: 4.35.1

package com.platform.gateway;

@com.google.protobuf.Generated
public interface ToolResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.ToolResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string call_id = 1 [json_name = "callId"];</code>
   * @return The callId.
   */
  java.lang.String getCallId();
  /**
   * <code>string call_id = 1 [json_name = "callId"];</code>
   * @return The bytes for callId.
   */
  com.google.protobuf.ByteString
      getCallIdBytes();

  /**
   * <pre>
   * success / failed / rejected / pending_approval
   * </pre>
   *
   * <code>string status = 2 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * success / failed / rejected / pending_approval
   * </pre>
   *
   * <code>string status = 2 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * 结果（JSON 字串）
   * </pre>
   *
   * <code>string result_json = 3 [json_name = "resultJson"];</code>
   * @return The resultJson.
   */
  java.lang.String getResultJson();
  /**
   * <pre>
   * 结果（JSON 字串）
   * </pre>
   *
   * <code>string result_json = 3 [json_name = "resultJson"];</code>
   * @return The bytes for resultJson.
   */
  com.google.protobuf.ByteString
      getResultJsonBytes();

  /**
   * <pre>
   * 审批 ID（如需要审批）
   * </pre>
   *
   * <code>string approval_id = 4 [json_name = "approvalId"];</code>
   * @return The approvalId.
   */
  java.lang.String getApprovalId();
  /**
   * <pre>
   * 审批 ID（如需要审批）
   * </pre>
   *
   * <code>string approval_id = 4 [json_name = "approvalId"];</code>
   * @return The bytes for approvalId.
   */
  com.google.protobuf.ByteString
      getApprovalIdBytes();

  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 5 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 5 [json_name = "error"];</code>
   * @return The error.
   */
  com.platform.common.ErrorDetail getError();
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.common.ErrorDetail error = 5 [json_name = "error"];</code>
   */
  com.platform.common.ErrorDetailOrBuilder getErrorOrBuilder();
}
