/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as ApprovalIndexRouteImport } from './routes/approval/index'
import { Route as UsersRolesRouteImport } from './routes/users/roles'
import { Route as ToolsRegisterRouteImport } from './routes/tools/register'
import { Route as ToolsNameRouteImport } from './routes/tools/$name'
import { Route as ChatSessionIdRouteImport } from './routes/chat/$sessionId'
import { Route as ApprovalIdRouteImport } from './routes/approval/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalIndexRoute = ApprovalIndexRouteImport.update({
  id: '/approval/',
  path: '/approval/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRolesRoute = UsersRolesRouteImport.update({
  id: '/users/roles',
  path: '/users/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRegisterRoute = ToolsRegisterRouteImport.update({
  id: '/tools/register',
  path: '/tools/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNameRoute = ToolsNameRouteImport.update({
  id: '/tools/$name',
  path: '/tools/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalIdRoute = ApprovalIdRouteImport.update({
  id: '/approval/$id',
  path: '/approval/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/approval/$id': typeof ApprovalIdRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/tools/$name': typeof ToolsNameRoute
  '/tools/register': typeof ToolsRegisterRoute
  '/users/roles': typeof UsersRolesRoute
  '/approval/': typeof ApprovalIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/approval/$id': typeof ApprovalIdRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/tools/$name': typeof ToolsNameRoute
  '/tools/register': typeof ToolsRegisterRoute
  '/users/roles': typeof UsersRolesRoute
  '/approval': typeof ApprovalIndexRoute
  '/audit': typeof AuditIndexRoute
  '/chat': typeof ChatIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/approval/$id': typeof ApprovalIdRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/tools/$name': typeof ToolsNameRoute
  '/tools/register': typeof ToolsRegisterRoute
  '/users/roles': typeof UsersRolesRoute
  '/approval/': typeof ApprovalIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/approval/$id'
    | '/chat/$sessionId'
    | '/tools/$name'
    | '/tools/register'
    | '/users/roles'
    | '/approval/'
    | '/audit/'
    | '/chat/'
    | '/dashboard/'
    | '/notifications/'
    | '/tools/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/approval/$id'
    | '/chat/$sessionId'
    | '/tools/$name'
    | '/tools/register'
    | '/users/roles'
    | '/approval'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/notifications'
    | '/tools'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/forbidden'
    | '/login'
    | '/approval/$id'
    | '/chat/$sessionId'
    | '/tools/$name'
    | '/tools/register'
    | '/users/roles'
    | '/approval/'
    | '/audit/'
    | '/chat/'
    | '/dashboard/'
    | '/notifications/'
    | '/tools/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  ApprovalIdRoute: typeof ApprovalIdRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
  ToolsNameRoute: typeof ToolsNameRoute
  ToolsRegisterRoute: typeof ToolsRegisterRoute
  UsersRolesRoute: typeof UsersRolesRoute
  ApprovalIndexRoute: typeof ApprovalIndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/': {
      id: '/approval/'
      path: '/approval'
      fullPath: '/approval/'
      preLoaderRoute: typeof ApprovalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/roles': {
      id: '/users/roles'
      path: '/users/roles'
      fullPath: '/users/roles'
      preLoaderRoute: typeof UsersRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/register': {
      id: '/tools/register'
      path: '/tools/register'
      fullPath: '/tools/register'
      preLoaderRoute: typeof ToolsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$name': {
      id: '/tools/$name'
      path: '/tools/$name'
      fullPath: '/tools/$name'
      preLoaderRoute: typeof ToolsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/$id': {
      id: '/approval/$id'
      path: '/approval/$id'
      fullPath: '/approval/$id'
      preLoaderRoute: typeof ApprovalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  ApprovalIdRoute: ApprovalIdRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
  ToolsNameRoute: ToolsNameRoute,
  ToolsRegisterRoute: ToolsRegisterRoute,
  UsersRolesRoute: UsersRolesRoute,
  ApprovalIndexRoute: ApprovalIndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
