// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model/model_gateway.proto
// Protobuf Java Version: 4.35.0

package com.platform.model;

@com.google.protobuf.Generated
public interface GetTokenQuotaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.GetTokenQuotaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  com.platform.model.RequestContext getContext();
  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   */
  com.platform.model.RequestContextOrBuilder getContextOrBuilder();

  /**
   * <pre>
   * 配额层级
   * </pre>
   *
   * <code>.model.QuotaLevel level = 2 [json_name = "level"];</code>
   * @return The enum numeric value on the wire for level.
   */
  int getLevelValue();
  /**
   * <pre>
   * 配额层级
   * </pre>
   *
   * <code>.model.QuotaLevel level = 2 [json_name = "level"];</code>
   * @return The level.
   */
  com.platform.model.QuotaLevel getLevel();

  /**
   * <pre>
   * 目标 ID（用户/租户）
   * </pre>
   *
   * <code>string target_id = 3 [json_name = "targetId"];</code>
   * @return The targetId.
   */
  java.lang.String getTargetId();
  /**
   * <pre>
   * 目标 ID（用户/租户）
   * </pre>
   *
   * <code>string target_id = 3 [json_name = "targetId"];</code>
   * @return The bytes for targetId.
   */
  com.google.protobuf.ByteString
      getTargetIdBytes();
}
