// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model/model_gateway.proto
// Protobuf Java Version: 4.35.0

package com.platform.model;

/**
 * <pre>
 * ListModelsResponse
 * </pre>
 *
 * Protobuf type {@code model.ListModelsResponse}
 */
@com.google.protobuf.Generated
public final class ListModelsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:model.ListModelsResponse)
    ListModelsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "ListModelsResponse");
  }
  // Use ListModelsResponse.newBuilder() to construct.
  private ListModelsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListModelsResponse() {
    models_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platform.model.ModelGateway.internal_static_model_ListModelsResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.platform.model.ModelGateway.internal_static_model_ListModelsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platform.model.ModelGateway.internal_static_model_ListModelsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platform.model.ListModelsResponse.class, com.platform.model.ListModelsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CONTEXT_FIELD_NUMBER = 1;
  private com.platform.model.RequestContext context_;
  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  @java.lang.Override
  public boolean hasContext() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  @java.lang.Override
  public com.platform.model.RequestContext getContext() {
    return context_ == null ? com.platform.model.RequestContext.getDefaultInstance() : context_;
  }
  /**
   * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
   */
  @java.lang.Override
  public com.platform.model.RequestContextOrBuilder getContextOrBuilder() {
    return context_ == null ? com.platform.model.RequestContext.getDefaultInstance() : context_;
  }

  public static final int MODELS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.platform.model.ModelInfo> models_;
  /**
   * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
   */
  @java.lang.Override
  public java.util.List<com.platform.model.ModelInfo> getModelsList() {
    return models_;
  }
  /**
   * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.platform.model.ModelInfoOrBuilder> 
      getModelsOrBuilderList() {
    return models_;
  }
  /**
   * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
   */
  @java.lang.Override
  public int getModelsCount() {
    return models_.size();
  }
  /**
   * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
   */
  @java.lang.Override
  public com.platform.model.ModelInfo getModels(int index) {
    return models_.get(index);
  }
  /**
   * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
   */
  @java.lang.Override
  public com.platform.model.ModelInfoOrBuilder getModelsOrBuilder(
      int index) {
    return models_.get(index);
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 3;
  private int totalCount_ = 0;
  /**
   * <code>int32 total_count = 3 [json_name = "totalCount"];</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public int getTotalCount() {
    return totalCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getContext());
    }
    for (int i = 0; i < models_.size(); i++) {
      output.writeMessage(2, models_.get(i));
    }
    if (totalCount_ != 0) {
      output.writeInt32(3, totalCount_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContext());
    }

        {
          final int count = models_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(models_.get(i));
          }
          size += 1 * count;
        }
    if (totalCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalCount_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platform.model.ListModelsResponse)) {
      return super.equals(obj);
    }
    com.platform.model.ListModelsResponse other = (com.platform.model.ListModelsResponse) obj;

    if (hasContext() != other.hasContext()) return false;
    if (hasContext()) {
      if (!getContext()
          .equals(other.getContext())) return false;
    }
    if (!getModelsList()
        .equals(other.getModelsList())) return false;
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContext()) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
    }
    if (getModelsCount() > 0) {
      hash = (37 * hash) + MODELS_FIELD_NUMBER;
      hash = (53 * hash) + getModelsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platform.model.ListModelsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.model.ListModelsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.model.ListModelsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.model.ListModelsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.model.ListModelsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platform.model.ListModelsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platform.model.ListModelsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.platform.model.ListModelsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.platform.model.ListModelsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.platform.model.ListModelsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platform.model.ListModelsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.platform.model.ListModelsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platform.model.ListModelsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ListModelsResponse
   * </pre>
   *
   * Protobuf type {@code model.ListModelsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.ListModelsResponse)
      com.platform.model.ListModelsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platform.model.ModelGateway.internal_static_model_ListModelsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platform.model.ModelGateway.internal_static_model_ListModelsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platform.model.ListModelsResponse.class, com.platform.model.ListModelsResponse.Builder.class);
    }

    // Construct using com.platform.model.ListModelsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetContextFieldBuilder();
        internalGetModelsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      if (modelsBuilder_ == null) {
        models_ = java.util.Collections.emptyList();
      } else {
        models_ = null;
        modelsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      totalCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platform.model.ModelGateway.internal_static_model_ListModelsResponse_descriptor;
    }

    @java.lang.Override
    public com.platform.model.ListModelsResponse getDefaultInstanceForType() {
      return com.platform.model.ListModelsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.platform.model.ListModelsResponse build() {
      com.platform.model.ListModelsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platform.model.ListModelsResponse buildPartial() {
      com.platform.model.ListModelsResponse result = new com.platform.model.ListModelsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.platform.model.ListModelsResponse result) {
      if (modelsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          models_ = java.util.Collections.unmodifiableList(models_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.models_ = models_;
      } else {
        result.models_ = modelsBuilder_.build();
      }
    }

    private void buildPartial0(com.platform.model.ListModelsResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.context_ = contextBuilder_ == null
            ? context_
            : contextBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalCount_ = totalCount_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platform.model.ListModelsResponse) {
        return mergeFrom((com.platform.model.ListModelsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platform.model.ListModelsResponse other) {
      if (other == com.platform.model.ListModelsResponse.getDefaultInstance()) return this;
      if (other.hasContext()) {
        mergeContext(other.getContext());
      }
      if (modelsBuilder_ == null) {
        if (!other.models_.isEmpty()) {
          if (models_.isEmpty()) {
            models_ = other.models_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureModelsIsMutable();
            models_.addAll(other.models_);
          }
          onChanged();
        }
      } else {
        if (!other.models_.isEmpty()) {
          if (modelsBuilder_.isEmpty()) {
            modelsBuilder_.dispose();
            modelsBuilder_ = null;
            models_ = other.models_;
            bitField0_ = (bitField0_ & ~0x00000002);
            modelsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetModelsFieldBuilder() : null;
          } else {
            modelsBuilder_.addAllMessages(other.models_);
          }
        }
      }
      if (other.getTotalCount() != 0) {
        setTotalCount(other.getTotalCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetContextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.platform.model.ModelInfo m =
                  input.readMessage(
                      com.platform.model.ModelInfo.parser(),
                      extensionRegistry);
              if (modelsBuilder_ == null) {
                ensureModelsIsMutable();
                models_.add(m);
              } else {
                modelsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              totalCount_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.platform.model.RequestContext context_;
    private com.google.protobuf.SingleFieldBuilder<
        com.platform.model.RequestContext, com.platform.model.RequestContext.Builder, com.platform.model.RequestContextOrBuilder> contextBuilder_;
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     * @return Whether the context field is set.
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     * @return The context.
     */
    public com.platform.model.RequestContext getContext() {
      if (contextBuilder_ == null) {
        return context_ == null ? com.platform.model.RequestContext.getDefaultInstance() : context_;
      } else {
        return contextBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder setContext(com.platform.model.RequestContext value) {
      if (contextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        context_ = value;
      } else {
        contextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder setContext(
        com.platform.model.RequestContext.Builder builderForValue) {
      if (contextBuilder_ == null) {
        context_ = builderForValue.build();
      } else {
        contextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder mergeContext(com.platform.model.RequestContext value) {
      if (contextBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          context_ != null &&
          context_ != com.platform.model.RequestContext.getDefaultInstance()) {
          getContextBuilder().mergeFrom(value);
        } else {
          context_ = value;
        }
      } else {
        contextBuilder_.mergeFrom(value);
      }
      if (context_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     */
    public Builder clearContext() {
      bitField0_ = (bitField0_ & ~0x00000001);
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     */
    public com.platform.model.RequestContext.Builder getContextBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     */
    public com.platform.model.RequestContextOrBuilder getContextOrBuilder() {
      if (contextBuilder_ != null) {
        return contextBuilder_.getMessageOrBuilder();
      } else {
        return context_ == null ?
            com.platform.model.RequestContext.getDefaultInstance() : context_;
      }
    }
    /**
     * <code>.model.RequestContext context = 1 [json_name = "context"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.platform.model.RequestContext, com.platform.model.RequestContext.Builder, com.platform.model.RequestContextOrBuilder> 
        internalGetContextFieldBuilder() {
      if (contextBuilder_ == null) {
        contextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.platform.model.RequestContext, com.platform.model.RequestContext.Builder, com.platform.model.RequestContextOrBuilder>(
                getContext(),
                getParentForChildren(),
                isClean());
        context_ = null;
      }
      return contextBuilder_;
    }

    private java.util.List<com.platform.model.ModelInfo> models_ =
      java.util.Collections.emptyList();
    private void ensureModelsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        models_ = new java.util.ArrayList<com.platform.model.ModelInfo>(models_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.platform.model.ModelInfo, com.platform.model.ModelInfo.Builder, com.platform.model.ModelInfoOrBuilder> modelsBuilder_;

    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public java.util.List<com.platform.model.ModelInfo> getModelsList() {
      if (modelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(models_);
      } else {
        return modelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public int getModelsCount() {
      if (modelsBuilder_ == null) {
        return models_.size();
      } else {
        return modelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public com.platform.model.ModelInfo getModels(int index) {
      if (modelsBuilder_ == null) {
        return models_.get(index);
      } else {
        return modelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder setModels(
        int index, com.platform.model.ModelInfo value) {
      if (modelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelsIsMutable();
        models_.set(index, value);
        onChanged();
      } else {
        modelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder setModels(
        int index, com.platform.model.ModelInfo.Builder builderForValue) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        models_.set(index, builderForValue.build());
        onChanged();
      } else {
        modelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder addModels(com.platform.model.ModelInfo value) {
      if (modelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelsIsMutable();
        models_.add(value);
        onChanged();
      } else {
        modelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder addModels(
        int index, com.platform.model.ModelInfo value) {
      if (modelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelsIsMutable();
        models_.add(index, value);
        onChanged();
      } else {
        modelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder addModels(
        com.platform.model.ModelInfo.Builder builderForValue) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        models_.add(builderForValue.build());
        onChanged();
      } else {
        modelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder addModels(
        int index, com.platform.model.ModelInfo.Builder builderForValue) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        models_.add(index, builderForValue.build());
        onChanged();
      } else {
        modelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder addAllModels(
        java.lang.Iterable<? extends com.platform.model.ModelInfo> values) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, models_);
        onChanged();
      } else {
        modelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder clearModels() {
      if (modelsBuilder_ == null) {
        models_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        modelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public Builder removeModels(int index) {
      if (modelsBuilder_ == null) {
        ensureModelsIsMutable();
        models_.remove(index);
        onChanged();
      } else {
        modelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public com.platform.model.ModelInfo.Builder getModelsBuilder(
        int index) {
      return internalGetModelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public com.platform.model.ModelInfoOrBuilder getModelsOrBuilder(
        int index) {
      if (modelsBuilder_ == null) {
        return models_.get(index);  } else {
        return modelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public java.util.List<? extends com.platform.model.ModelInfoOrBuilder> 
         getModelsOrBuilderList() {
      if (modelsBuilder_ != null) {
        return modelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(models_);
      }
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public com.platform.model.ModelInfo.Builder addModelsBuilder() {
      return internalGetModelsFieldBuilder().addBuilder(
          com.platform.model.ModelInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public com.platform.model.ModelInfo.Builder addModelsBuilder(
        int index) {
      return internalGetModelsFieldBuilder().addBuilder(
          index, com.platform.model.ModelInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .model.ModelInfo models = 2 [json_name = "models"];</code>
     */
    public java.util.List<com.platform.model.ModelInfo.Builder> 
         getModelsBuilderList() {
      return internalGetModelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.platform.model.ModelInfo, com.platform.model.ModelInfo.Builder, com.platform.model.ModelInfoOrBuilder> 
        internalGetModelsFieldBuilder() {
      if (modelsBuilder_ == null) {
        modelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.platform.model.ModelInfo, com.platform.model.ModelInfo.Builder, com.platform.model.ModelInfoOrBuilder>(
                models_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        models_ = null;
      }
      return modelsBuilder_;
    }

    private int totalCount_ ;
    /**
     * <code>int32 total_count = 3 [json_name = "totalCount"];</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>int32 total_count = 3 [json_name = "totalCount"];</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(int value) {

      totalCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_count = 3 [json_name = "totalCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:model.ListModelsResponse)
  }

  // @@protoc_insertion_point(class_scope:model.ListModelsResponse)
  private static final com.platform.model.ListModelsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platform.model.ListModelsResponse();
  }

  public static com.platform.model.ListModelsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListModelsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListModelsResponse>() {
    @java.lang.Override
    public ListModelsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListModelsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListModelsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platform.model.ListModelsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

