// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model/model_gateway.proto
// Protobuf Java Version: 4.35.0

package com.platform.model;

@com.google.protobuf.Generated
public final class ModelGateway extends com.google.protobuf.GeneratedFile {
  private ModelGateway() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "ModelGateway");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_RequestContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_RequestContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ContentPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ContentPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ToolDefinition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ToolDefinition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ToolCallResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ToolCallResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ChatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ChatStreamChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ChatStreamChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ListModelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ListModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ModelInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ModelInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ListModelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_ListModelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_GetTokenQuotaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_GetTokenQuotaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_GetTokenQuotaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_GetTokenQuotaResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031model/model_gateway.proto\022\005model\032\027comm" +
      "on/error_code.proto\"\266\001\n\016RequestContext\022\035" +
      "\n\nrequest_id\030\001 \001(\tR\trequestId\022\033\n\ttenant_" +
      "id\030\002 \001(\tR\010tenantId\022\027\n\007user_id\030\003 \001(\tR\006use" +
      "rId\022\031\n\010trace_id\030\004 \001(\tR\007traceId\022\035\n\nsessio" +
      "n_id\030\005 \001(\tR\tsessionId\022\025\n\006run_id\030\006 \001(\tR\005r" +
      "unId\"\222\004\n\013ChatRequest\022/\n\007context\030\001 \001(\0132\025." +
      "model.RequestContextR\007context\022*\n\010message" +
      "s\030\002 \003(\0132\016.model.MessageR\010messages\022\024\n\005mod" +
      "el\030\003 \001(\tR\005model\022\024\n\005scene\030\004 \001(\tR\005scene\022%\n" +
      "\016routing_policy\030\005 \001(\tR\rroutingPolicy\022 \n\013" +
      "temperature\030\006 \001(\002R\013temperature\022\035\n\nmax_to" +
      "kens\030\007 \001(\005R\tmaxTokens\022\023\n\005top_p\030\010 \001(\002R\004to" +
      "pP\022\022\n\004stop\030\t \003(\tR\004stop\022\022\n\004seed\030\n \001(\005R\004se" +
      "ed\022\'\n\017response_format\030\013 \001(\tR\016responseFor" +
      "mat\022\037\n\013json_schema\030\014 \001(\tR\njsonSchema\022+\n\005" +
      "tools\030\r \003(\0132\025.model.ToolDefinitionR\005tool" +
      "s\022\037\n\013tool_choice\030\016 \001(\tR\ntoolChoice\022\026\n\006st" +
      "ream\030\017 \001(\010R\006stream\022%\n\016enable_caching\030\020 \001" +
      "(\010R\renableCaching\"\271\001\n\007Message\022\022\n\004role\030\001 " +
      "\001(\tR\004role\022\030\n\007content\030\002 \001(\tR\007content\022(\n\005p" +
      "arts\030\003 \003(\0132\022.model.ContentPartR\005parts\0224\n" +
      "\ntool_calls\030\004 \003(\0132\025.model.ToolCallResult" +
      "R\ttoolCalls\022 \n\014tool_call_id\030\005 \001(\tR\ntoolC" +
      "allId\"\224\001\n\013ContentPart\022\022\n\004type\030\001 \001(\tR\004typ" +
      "e\022\022\n\004text\030\002 \001(\tR\004text\022\033\n\timage_url\030\003 \001(\t" +
      "R\010imageUrl\022!\n\014image_base64\030\004 \001(\tR\013imageB" +
      "ase64\022\035\n\nmedia_type\030\005 \001(\tR\tmediaType\"\207\001\n" +
      "\016ToolDefinition\022\022\n\004type\030\001 \001(\tR\004type\022\022\n\004n" +
      "ame\030\002 \001(\tR\004name\022 \n\013description\030\003 \001(\tR\013de" +
      "scription\022+\n\021parameters_schema\030\004 \001(\tR\020pa" +
      "rametersSchema\"o\n\016ToolCallResult\022\027\n\007call" +
      "_id\030\001 \001(\tR\006callId\022\022\n\004type\030\002 \001(\tR\004type\022\022\n" +
      "\004name\030\003 \001(\tR\004name\022\034\n\targuments\030\004 \001(\tR\tar" +
      "guments\"\330\004\n\014ChatResponse\022/\n\007context\030\001 \001(" +
      "\0132\025.model.RequestContextR\007context\022\037\n\013res" +
      "ponse_id\030\002 \001(\tR\nresponseId\022\030\n\007content\030\003 " +
      "\001(\tR\007content\022(\n\005parts\030\004 \003(\0132\022.model.Cont" +
      "entPartR\005parts\0224\n\ntool_calls\030\005 \003(\0132\025.mod" +
      "el.ToolCallResultR\ttoolCalls\022\035\n\nmodel_us" +
      "ed\030\006 \001(\tR\tmodelUsed\022\032\n\010provider\030\007 \001(\tR\010p" +
      "rovider\022#\n\rprompt_tokens\030\010 \001(\005R\014promptTo" +
      "kens\022+\n\021completion_tokens\030\t \001(\005R\020complet" +
      "ionTokens\022!\n\014total_tokens\030\n \001(\005R\013totalTo" +
      "kens\022#\n\rcached_tokens\030\013 \001(\005R\014cachedToken" +
      "s\022\031\n\010cost_usd\030\014 \001(\002R\007costUsd\022#\n\rfinish_r" +
      "eason\030\r \001(\tR\014finishReason\022\035\n\nlatency_ms\030" +
      "\016 \001(\005R\tlatencyMs\022\035\n\ncreated_at\030\017 \001(\003R\tcr" +
      "eatedAt\022)\n\005error\030\020 \001(\0132\023.common.ErrorDet" +
      "ailR\005error\"\240\003\n\017ChatStreamChunk\022/\n\007contex" +
      "t\030\001 \001(\0132\025.model.RequestContextR\007context\022" +
      "\037\n\013response_id\030\002 \001(\tR\nresponseId\022\037\n\013chun" +
      "k_index\030\003 \001(\005R\nchunkIndex\022\024\n\005delta\030\004 \001(\t" +
      "R\005delta\022?\n\020tool_call_deltas\030\005 \003(\0132\025.mode" +
      "l.ToolCallResultR\016toolCallDeltas\022#\n\rfini" +
      "sh_reason\030\006 \001(\tR\014finishReason\022#\n\rprompt_" +
      "tokens\030\007 \001(\005R\014promptTokens\022+\n\021completion" +
      "_tokens\030\010 \001(\005R\020completionTokens\022!\n\014total" +
      "_tokens\030\t \001(\005R\013totalTokens\022)\n\005error\030\n \001(" +
      "\0132\023.common.ErrorDetailR\005error\"\213\001\n\021ListMo" +
      "delsRequest\022/\n\007context\030\001 \001(\0132\025.model.Req" +
      "uestContextR\007context\022\032\n\010provider\030\002 \001(\tR\010" +
      "provider\022)\n\020include_inactive\030\003 \001(\010R\017incl" +
      "udeInactive\"\376\004\n\tModelInfo\022\031\n\010model_id\030\001 " +
      "\001(\tR\007modelId\022\032\n\010provider\030\002 \001(\tR\010provider" +
      "\022!\n\014display_name\030\003 \001(\tR\013displayName\022 \n\013d" +
      "escription\030\004 \001(\tR\013description\022,\n\022support" +
      "s_tool_call\030\005 \001(\010R\020supportsToolCall\022\'\n\017s" +
      "upports_vision\030\006 \001(\010R\016supportsVision\022-\n\022" +
      "supports_streaming\030\007 \001(\010R\021supportsStream" +
      "ing\0220\n\024supports_json_output\030\010 \001(\010R\022suppo" +
      "rtsJsonOutput\022,\n\022max_context_tokens\030\t \001(" +
      "\005R\020maxContextTokens\022*\n\021max_output_tokens" +
      "\030\n \001(\005R\017maxOutputTokens\022\026\n\006status\030\013 \001(\tR" +
      "\006status\022!\n\014is_available\030\014 \001(\010R\013isAvailab" +
      "le\022+\n\022input_price_per_1k\030\r \001(\002R\017inputPri" +
      "cePer1k\022-\n\023output_price_per_1k\030\016 \001(\002R\020ou" +
      "tputPricePer1k\022-\n\023cached_price_per_1k\030\017 " +
      "\001(\002R\020cachedPricePer1k\022\035\n\nupdated_at\030\020 \001(" +
      "\003R\tupdatedAt\"\220\001\n\022ListModelsResponse\022/\n\007c" +
      "ontext\030\001 \001(\0132\025.model.RequestContextR\007con" +
      "text\022(\n\006models\030\002 \003(\0132\020.model.ModelInfoR\006" +
      "models\022\037\n\013total_count\030\003 \001(\005R\ntotalCount\"" +
      "\215\001\n\024GetTokenQuotaRequest\022/\n\007context\030\001 \001(" +
      "\0132\025.model.RequestContextR\007context\022\'\n\005lev" +
      "el\030\002 \001(\0162\021.model.QuotaLevelR\005level\022\033\n\tta" +
      "rget_id\030\003 \001(\tR\010targetId\"\274\002\n\025GetTokenQuot" +
      "aResponse\022/\n\007context\030\001 \001(\0132\025.model.Reque" +
      "stContextR\007context\022\026\n\006budget\030\002 \001(\003R\006budg" +
      "et\022\022\n\004used\030\003 \001(\003R\004used\022\034\n\tremaining\030\004 \001(" +
      "\003R\tremaining\022)\n\020usage_percentage\030\005 \001(\002R\017" +
      "usagePercentage\022\032\n\010exceeded\030\006 \001(\010R\010excee" +
      "ded\022\'\n\017exceeded_action\030\007 \001(\tR\016exceededAc" +
      "tion\022\031\n\010reset_at\030\010 \001(\003R\007resetAt\022\035\n\nupdat" +
      "ed_at\030\t \001(\003R\tupdatedAt*\210\001\n\nQuotaLevel\022\033\n" +
      "\027QUOTA_LEVEL_UNSPECIFIED\020\000\022\027\n\023QUOTA_LEVE" +
      "L_SESSION\020\001\022\024\n\020QUOTA_LEVEL_USER\020\002\022\026\n\022QUO" +
      "TA_LEVEL_TENANT\020\003\022\026\n\022QUOTA_LEVEL_GLOBAL\020" +
      "\0042\245\002\n\023ModelGatewayService\0229\n\016ChatComplet" +
      "ion\022\022.model.ChatRequest\032\023.model.ChatResp" +
      "onse\022D\n\024StreamChatCompletion\022\022.model.Cha" +
      "tRequest\032\026.model.ChatStreamChunk0\001\022A\n\nLi" +
      "stModels\022\030.model.ListModelsRequest\032\031.mod" +
      "el.ListModelsResponse\022J\n\rGetTokenQuota\022\033" +
      ".model.GetTokenQuotaRequest\032\034.model.GetT" +
      "okenQuotaResponseB\026\n\022com.platform.modelP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.platform.common.ErrorCodeOuterClass.getDescriptor(),
        });
    internal_static_model_RequestContext_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_model_RequestContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_RequestContext_descriptor,
        new java.lang.String[] { "RequestId", "TenantId", "UserId", "TraceId", "SessionId", "RunId", });
    internal_static_model_ChatRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_model_ChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ChatRequest_descriptor,
        new java.lang.String[] { "Context", "Messages", "Model", "Scene", "RoutingPolicy", "Temperature", "MaxTokens", "TopP", "Stop", "Seed", "ResponseFormat", "JsonSchema", "Tools", "ToolChoice", "Stream", "EnableCaching", });
    internal_static_model_Message_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_model_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_Message_descriptor,
        new java.lang.String[] { "Role", "Content", "Parts", "ToolCalls", "ToolCallId", });
    internal_static_model_ContentPart_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_model_ContentPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ContentPart_descriptor,
        new java.lang.String[] { "Type", "Text", "ImageUrl", "ImageBase64", "MediaType", });
    internal_static_model_ToolDefinition_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_model_ToolDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ToolDefinition_descriptor,
        new java.lang.String[] { "Type", "Name", "Description", "ParametersSchema", });
    internal_static_model_ToolCallResult_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_model_ToolCallResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ToolCallResult_descriptor,
        new java.lang.String[] { "CallId", "Type", "Name", "Arguments", });
    internal_static_model_ChatResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_model_ChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ChatResponse_descriptor,
        new java.lang.String[] { "Context", "ResponseId", "Content", "Parts", "ToolCalls", "ModelUsed", "Provider", "PromptTokens", "CompletionTokens", "TotalTokens", "CachedTokens", "CostUsd", "FinishReason", "LatencyMs", "CreatedAt", "Error", });
    internal_static_model_ChatStreamChunk_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_model_ChatStreamChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ChatStreamChunk_descriptor,
        new java.lang.String[] { "Context", "ResponseId", "ChunkIndex", "Delta", "ToolCallDeltas", "FinishReason", "PromptTokens", "CompletionTokens", "TotalTokens", "Error", });
    internal_static_model_ListModelsRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_model_ListModelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ListModelsRequest_descriptor,
        new java.lang.String[] { "Context", "Provider", "IncludeInactive", });
    internal_static_model_ModelInfo_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_model_ModelInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ModelInfo_descriptor,
        new java.lang.String[] { "ModelId", "Provider", "DisplayName", "Description", "SupportsToolCall", "SupportsVision", "SupportsStreaming", "SupportsJsonOutput", "MaxContextTokens", "MaxOutputTokens", "Status", "IsAvailable", "InputPricePer1K", "OutputPricePer1K", "CachedPricePer1K", "UpdatedAt", });
    internal_static_model_ListModelsResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_model_ListModelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_ListModelsResponse_descriptor,
        new java.lang.String[] { "Context", "Models", "TotalCount", });
    internal_static_model_GetTokenQuotaRequest_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_model_GetTokenQuotaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_GetTokenQuotaRequest_descriptor,
        new java.lang.String[] { "Context", "Level", "TargetId", });
    internal_static_model_GetTokenQuotaResponse_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_model_GetTokenQuotaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_GetTokenQuotaResponse_descriptor,
        new java.lang.String[] { "Context", "Budget", "Used", "Remaining", "UsagePercentage", "Exceeded", "ExceededAction", "ResetAt", "UpdatedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.platform.common.ErrorCodeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
