// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model/model_gateway.proto
// Protobuf Java Version: 4.35.0

package com.platform.model;

@com.google.protobuf.Generated
public interface ModelInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ModelInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 模型 ID（如 qwen-max）
   * </pre>
   *
   * <code>string model_id = 1 [json_name = "modelId"];</code>
   * @return The modelId.
   */
  java.lang.String getModelId();
  /**
   * <pre>
   * 模型 ID（如 qwen-max）
   * </pre>
   *
   * <code>string model_id = 1 [json_name = "modelId"];</code>
   * @return The bytes for modelId.
   */
  com.google.protobuf.ByteString
      getModelIdBytes();

  /**
   * <pre>
   * 提供商
   * </pre>
   *
   * <code>string provider = 2 [json_name = "provider"];</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <pre>
   * 提供商
   * </pre>
   *
   * <code>string provider = 2 [json_name = "provider"];</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <pre>
   * 显示名称
   * </pre>
   *
   * <code>string display_name = 3 [json_name = "displayName"];</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   * 显示名称
   * </pre>
   *
   * <code>string display_name = 3 [json_name = "displayName"];</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * 能力标记
   * </pre>
   *
   * <code>bool supports_tool_call = 5 [json_name = "supportsToolCall"];</code>
   * @return The supportsToolCall.
   */
  boolean getSupportsToolCall();

  /**
   * <code>bool supports_vision = 6 [json_name = "supportsVision"];</code>
   * @return The supportsVision.
   */
  boolean getSupportsVision();

  /**
   * <code>bool supports_streaming = 7 [json_name = "supportsStreaming"];</code>
   * @return The supportsStreaming.
   */
  boolean getSupportsStreaming();

  /**
   * <code>bool supports_json_output = 8 [json_name = "supportsJsonOutput"];</code>
   * @return The supportsJsonOutput.
   */
  boolean getSupportsJsonOutput();

  /**
   * <pre>
   * 限制
   * </pre>
   *
   * <code>int32 max_context_tokens = 9 [json_name = "maxContextTokens"];</code>
   * @return The maxContextTokens.
   */
  int getMaxContextTokens();

  /**
   * <code>int32 max_output_tokens = 10 [json_name = "maxOutputTokens"];</code>
   * @return The maxOutputTokens.
   */
  int getMaxOutputTokens();

  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>string status = 11 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>string status = 11 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * 当前是否可用
   * </pre>
   *
   * <code>bool is_available = 12 [json_name = "isAvailable"];</code>
   * @return The isAvailable.
   */
  boolean getIsAvailable();

  /**
   * <pre>
   * 定价（每 1000 tokens）
   * </pre>
   *
   * <code>float input_price_per_1k = 13 [json_name = "inputPricePer1k"];</code>
   * @return The inputPricePer1k.
   */
  float getInputPricePer1K();

  /**
   * <code>float output_price_per_1k = 14 [json_name = "outputPricePer1k"];</code>
   * @return The outputPricePer1k.
   */
  float getOutputPricePer1K();

  /**
   * <pre>
   * 缓存价格
   * </pre>
   *
   * <code>float cached_price_per_1k = 15 [json_name = "cachedPricePer1k"];</code>
   * @return The cachedPricePer1k.
   */
  float getCachedPricePer1K();

  /**
   * <code>int64 updated_at = 16 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  long getUpdatedAt();
}
